### ISSUE TITLE
[regression] (ios) notification permission popup is automatically displayed without user interaction

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#1006]
And when the user allows the permission, the state is not updated until the user chooses "refresh"
Please see attached video

https://github.com/e-mission/e-mission-docs/assets/2423263/e9eb7295-e657-4c3d-9850-dce0c65a2dda

**Comment by Abby-Wheelis** [comment]
I was just able to reproduce this issue in the emulator while logging in for the first time after re-installing the devapp, now I'm investigating why that might be happening. I don't see a reason at first glance how it could be launching without user interaction. 

The lack of update is likely due to the fact that I set the `useAppStateChange` hook up to use the app resuming foreground as the marker for a need to refresh. With the notification popup, we are probably not catching that the app left and resumed being in the foreground, I will look into this as well.

**Comment by Abby-Wheelis** [comment]
>I don't see a reason at first glance how it could be launching without user interaction.

I still haven't figured out why this is happening. When the checklist of permissions is set up, the `checkOrFix` method is called on each check to get the initial status. I was worried that we were accidentally calling the "fix" version of the location check instead of the "check" version, but I've verified with breakpoints that the only thing called without user interaction is `BEMDataCollection.isValidShowNotifications` just like the rest of the checks have their "isValid" method called. 

Next, I plan to look at the plugin to see if there could be a mistaken launch, and I will also check the change log of the `usePermissionStatus` where the checklist is controlled to see if I can identify what could have caused this regression.

**Comment by Abby-Wheelis** [comment]
>Next, I plan to look at the plugin to see if there could be a mistaken launch

The plugin code has not changed, so I don't see a reason why that could have caused a regression, but just so I can understand what's happening there, I traced what the permissions called to [this function](https://github.com/e-mission/e-mission-data-collection/blame/6a4d0d13bb64b25e0604793537c963cc454fd4aa/www/datacollection.js#L59)
```
isValidShowNotifications: function () {
        return new Promise(function(resolve, reject) {
            exec(resolve, reject, "DataCollection", "isValidShowNotifications", []);
        });
    }
```
I don't really know what `exec` does though, @shankari can you point me in the direction of where this code is housed?

**Comment by shankari** [comment]
https://github.com/e-mission/e-mission-data-collection, `src/ios`
@louisg1337 who has been working on the native code around onboarding (albeit on android) recently

**Comment by Abby-Wheelis** [comment]
Digging into these functions even further, some of the things it relies on seem to be deprecated: 
- `checkNotificationsEnabled` uses `currentUserNotificationSettings` which is deprecated for iOS 8-10 and the [documentation](https://developer.apple.com/documentation/uikit/uiapplication/1623092-currentusernotificationsettings) recommends `UNUserNotificationSettings` instead
- `checkAndPromptNotificationPermission` uses `registerUserNotificationSettings` which is also deprecated for iOS 8-10 and the [documentation](https://developer.apple.com/documentation/uikit/uiapplication/1622932-registerusernotificationsettings) recommends `requestAuthorization(options:completionHandler:)` and `setNotificationCategories(_:)` instead 

I haven't seen any reports of this causing the issue we have, though, so I'm not sure if this is the real problem.

**Comment by shankari** [comment]
@Abby-Wheelis
1. I think that it is very unlikely that this is a regression in the native code since that has not been changed for at least a year. 
2. the breakpoint in the code might also change the functionality by modifying the timing. Do you see the popup even with the breakpoint?
3. you can also add breakpoints in the native code, although that will require you to set up a native environment, which may be a lot of work.

**Comment by Abby-Wheelis** [comment]
>the breakpoint in the code might also change the functionality by modifying the timing. Do you see the popup even with the breakpoint?

Yes, one of the reasons that I'm so confused is that the breakpoint never trips to indicate that the function for fixing the has been called. I'll try looking more deeply into the logs, maybe that will help me find something I'm missing with just the breakpoint.

**Comment by Abby-Wheelis** [comment]
One of the things @JGreenlee brought up was testing agains earlier versions of the codebase to improve our ability to find out where this regression came from. On `master`, last updated about a week ago, with the old onboarding, does not show this behavior. Something else that we thought of was that it could be the case that whenever we interact with permissions (even just to check) it prompts the user. This is not the case, since we do check the permissions in order to set the colors and overall status up front. I also verified that pressing "refresh" for the notifications permission runs the check but does not create the prompt.

So as of the old onboarding, checking does not create the prompt and the prompt is not shown until the user clicks "fix".

**Comment by shankari** [comment]
> So as of the old onboarding, checking does not create the prompt and the prompt is not shown until the user clicks "fix".

Yup, that's why I marked it as a regression. At least it is reproducible. Regressions that are intermittent are the hardest to work with!

**Comment by Abby-Wheelis** [comment]
> At least it is reproducible. Regressions that are intermittent are the hardest to work with!

It is 100% reproducible, but I still can't identify how this is getting called. Looking at the log statements, the only things that are called are the "isValid" methods, and yet the popup still shows. The permission checks seem to be set up while the onboarding state is `route: 1` - I'm not sure if that's the same place they were set up before, or if that should matter. Here's a screenshot of the logs, let me know if something jumps out - I'm still looking for a place "fixShowNotifications" would show up, but I have yet to see that in the logs at all, and I'm not sure how that action from the plugin could be called without the fix method call from the phone code (that would have associated log statements)

![Screenshot 2023-10-10 at 4 57 28 PM](https://github.com/e-mission/e-mission-docs/assets/54848919/d8848f23-3a1e-4465-9f67-587e12aa9d2a)

Maybe the initialization in the hook is different that it was other places, is there a way that the function could be called during definition? Even if that were the case, though, I would still expect to see the log statements.

**Comment by Abby-Wheelis** [comment]
Still pretty stumped on what might be causing this regression. Is there any way that the plugin could be compiled/set-up differently in this branch? I know we made some changes to what we used from `e-mission-data-collection` when I re-wrote`collect-settings.js` and `sync-settings.js`. For the record, those files are still showing up for me in VS-code, even though we don't use them in this branch.

**Comment by Abby-Wheelis** [comment]
Ok, I don't think there is any way that this is a problem on the phone code. I just changed the code for the notification check such that both "fix" and "refresh" would both carry out the functionality for "refresh" (so there should be no way to call the fix method from the phone). And I still saw the popup!!! But if I click "don't allow" and then try and go back through and fix with the button, it just refreshes. 

However, the phone code is the only piece of this with recent changes, so I don't understand how it's NOT the phone code.

**Comment by JGreenlee** [comment]
So the act of 'refresh'ing the notification check does actually trigger the popup, even if we aren't trying to 'fix'.

I think the only explanation is that the old phone code (pre-regression) did not 'refresh' the notification check upfront, while now it does.

**Comment by JGreenlee** [comment]
In that case, I don't think we should go back to the pre-regression implementation. I think we **should** be refreshing the checks upfront so that we can accurately tell the user which items do or do not need to be addressed. 

The best path forward seems to be to make native changes to the plugin so it behaves as expected. Do we have the latitude to do this in the short term?

**Comment by Abby-Wheelis** [comment]
>I think the only explanation is that the old phone code (pre-regression) did not 'refresh' the notification check upfront, while now it does.

I checked that though, and found log statements that we had checked, and was able to click "refresh" for notifications before clicking "fix" and not see the popup, which is why I'm so confused.

**Comment by Abby-Wheelis** [comment]
For comparison's sake - here's a video and log from onboarding on both branches. Both branches check all the settings up front, which you can see in these log snippets. On `master`, I clicked "refresh" several times before I clicked fix and it did not make the poup show. 

|  `master` | `onboarding_routing_sept-2023`|
| ------------- | ------------- |
| ![Screenshot 2023-10-11 at 12 26 49 PM](https://github.com/e-mission/e-mission-docs/assets/54848919/1aa5dc08-3b5a-424f-8f52-f4da472e2860) | ![Screenshot 2023-10-11 at 12 30 30 PM](https://github.com/e-mission/e-mission-docs/assets/54848919/ba66b3c0-f245-40a0-a236-28b75b5adac7) |

https://github.com/e-mission/e-mission-docs/assets/54848919/03003fa8-07c1-43cd-b0da-465b331cedc6



https://github.com/e-mission/e-mission-docs/assets/54848919/098406e5-1cc3-41cf-bbb4-d411896e7860

**Comment by shankari** [comment]
Couple of comments:
1. > Is there any way that the plugin could be compiled/set-up differently in this branch? 
- the plugin is native code and is part of the devapp. If you haven't updated the devapp, the code has not changed.
2. does this happen on android as well? If so, the chances are high that it is a javascript change
3. if it does happen on android, you may still need to debug calls to the native code. @louisg1337 should be able to help with that

If it happens only on iOS, we should debug iOS native calls. @iantei may be able to help with that, or one of the people who wanted to work on the iOS native code. Or I can spend some time, but it is likely to be only next week.

**Comment by JGreenlee** [comment]
I don't think we even trigger a notification popup on Android devices, so this doesn't apply to them. The behavior on my Android devices is consistent with `master`.
- On my Android 10 and 11 phones, you don't have to do anything and notifications are already granted (this was before Android started requiring notifications permissions)
- On my Android 13 phone, there is no popup. Upon clicking "Fix", you're taken to "App Settings", and it appears green when you come back

**Comment by shankari** [comment]
So if this were a problem with the javascript making an additional call, I would expect that, on android 13, the "App Settings" screen would be popped up immediately as well. But that did not happen.

Instead, the "App Settings" only popped up when the user clicked "Fix". So I think that the issue is likely that, because of the rewrite, we are initializing some notification code as soon as the user clicks on "I Agree".  On iOS, some of the notification plugins automatically prompt for consent when you invoke them. I bet that is the source of the notification.

**Comment by shankari** [comment]
checking the iOS documentation, it looks like we do have to explicitly request permission using `registerUserNotificationSettings`

https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications

Quick check on which plugins are using this:


```
$ grep -r registerUserNotificationSettings plugins/
plugins//cordova-plugin-em-datacollection/src/ios/BEMAppDelegate.m:    if ([UIApplication instancesRespondToSelector:@selector(registerUserNotificationSettings:)]) {
plugins//cordova-plugin-em-datacollection/src/ios/BEMAppDelegate.m:        [[UIApplication sharedApplication] registerUserNotificationSettings:[UIUserNotificationSettings
plugins//cordova-plugin-em-datacollection/src/ios/Verification/SensorControlForegroundDelegate.m:        if ([UIApplication instancesRespondToSelector:@selector(registerUserNotificationSettings:)]) {
plugins//cordova-plugin-em-datacollection/src/ios/Verification/SensorControlForegroundDelegate.m:            [[UIApplication sharedApplication] registerUserNotificationSettings:requestedSettings];
```

and

```
$ grep -r requestAuthorization plugins/ 
plugins//@havesource/cordova-plugin-push/src/ios/PushPlugin.m:                [weakCenter requestAuthorizationWithOptions:authorizationOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {
plugins//cordova-plugin-badge-fix/src/ios/APPBadge.m:        [center requestAuthorizationWithOptions:options
plugins//cordova-plugin-local-notification-12/src/ios/APPLocalNotification.m:    [_center requestAuthorizationWithOptions:options completionHandler:^(BOOL granted, NSError* e) {
```

Of these, the ones in `SensorControlForegroundDelegate.m` are the ones that are called from the app status.
Any of the others could be causing the popup.

I would suggest the following steps to proceed:
- Figure out the plugin-level functions that are others are in, 
- Figure out where (if anywhere) they are called from the javascript code, and
- Figure out which of that javascript code is called when the user clicks on "I agree"

**Comment by Abby-Wheelis** [comment]
Thank you for the suggestion on how to proceed! Starting with:

>Figure out the plugin-level functions that are others are in,

- in `BEMAppDelegate.m` called in `didFinishLaunchingWithOptions`
- in `SensorControlForegroundDelegate.m` called in `checkAndPromptNotificationPermission` (as Shankari was saying, this is what clicking "fix" in the permissions causes
- in `PushPlugin.m` called in `handleNotificationSettingsWithAuthorizationOptions`
- in `APPBadge.m` called in `request`
- in `APPLocalNotification.m` called in `request`

I'm guessing that we don't call either of the plugin's request methods, since we have our own, but my next step is to figure out where each of these is called in our javascript code (if anywhere), and record that here. Then, I will try and set breakpoints at each of those places to see what is called.

**Comment by Abby-Wheelis** [comment]
I *might* have a better lead on where this could be called earlier than before, following from the first plugin call identified:  `didFininshLaunchingWithOptions` is called in `initWithConsent` in `markConsented` which in our JS code is called in startprefs by `writeConsentToNative` which is called in `markConsented` which is called in `ConsentPage` **when the user agrees**!

I'll work on breakpoints to ensure that this is the call, but it seems promising that this would be our culprit.

**Comment by JGreenlee** [comment]
In the old version, `markConsented()` was called in the `agree()` function of `intro.js`.

Counter-intuitively,`agree()` was not called by pressing "I agree" from the consent page. It was only called after pressing "I agree" on the permissions page.

This seems very likely the culprit. Do we want to revert to the counter-intuitive way, or do we want to fix the native code?

**Comment by Abby-Wheelis** [comment]
You're right that we always called `markConsented` but the stage at which we called it did change - on the consent page, before these changes the buttons either called `disagree` or `next`. Now they call `disagree` or `agree`. It's a little hard to tell, but it looks like `agree` was not called until they agreed to the permissions, but since that call seems to be embedded into the html it's hard for me to know for sure by just looking. I'll set breakpoints on `master` to confirm. Just confirmed on master that `agree` (and this `markConsented` popup ramification) are not called until post-permissions

**Comment by shankari** [comment]
@JGreenlee I don't think that the native code is wrong, we only want to initialize the FSM after we have all the permissions.
The reason that the `agree` method is not called on "I agree" is that it used to be called on "I agree", which would then lead to a bunch of popups (in the old days when permissions were all in popups). But when I added the consent screen, it seemed like people were not really consenting until they actually gave the permissions.

We tell people we are going to read their location all the time, but it is in a giant wall of text. Unless they actually click on "allow all the time", do they know what they are getting into?

So we should still only markConsented after all the permissions are in place so that the FSM can be initialized properly. But we can change the name of the function from `agree` to `consented` or `permitted` if that makes it more clear.

**Comment by Abby-Wheelis** [comment]
It makes sense to me that we would wait to fully register the user until they are "fully consented" to use of the all (including permissions). I think renaming is definitely a good idea. I can work on that now, and would plan to likely move the function from `ConsentPage` as well, so that 'agree()' just advances the onboardingState. I think the best place for this `markConsented` would then be as soon as the permissions are agreed to. Would it make sense to wrap it into `useEffect` on the `saveQR` page? Then the login and the consent marking would happen in quick sucession as soon as the permissions are enabled. 

That would, however, not require clicking the button to close the modal, so I could move "marking consent" into the permissions modal, to be executed when the user closes the modal if consent has not already been marked.

I could see either of these working, with the latter being the most accurate to what we had before. @shankari @JGreenlee do either of you have one of those options you prefer or a different idea of where we should move it to?

**Comment by Abby-Wheelis** [comment]
After the patch, this is no longer happening on staging, I tested by uninstalling the app and reinstalling, during onboarding I did not see the popup until I clicked "fix", as seen in the emulator [here](https://github.com/e-mission/e-mission-phone/pull/1071#issuecomment-1769497330). This patch also resolved the issue about the checks not reloading/turning green at first. The checks change as soon as the permission is changed - even on the ones where we don't "leave" the app and there is just a popup (like notifications on iPhone)
