### ISSUE TITLE
Consent deletion is not handled gracefully

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#228]
After investigating and fixing https://github.com/e-mission/cordova-jwt-auth/issues/8, we found that it had at least two occurrences in the real world. Furthermore, the users reported that:

1. they never got notifications about the data collection being suspended due to no consent
1. even after the fix was in, data collection was not resumed because:
   1. although the token is now valid, the consent is in the localStorage, although not in the native code, so we move on to the metrics
   1. the remote pushes have stopped because we don't register for them if we are not consented, so the consent document from the server is never retrieved

We just really need to make the consent thing a lot better.

**Comment by MythriNagaraju** [comment]
I probably should not be commenting on a closed issue - but is there a way to completely delete the consent process? Since I could not find a simple way to do this in my custom client, I marked consent in the code, but it still expects user consent to re-start data collection when data collection is paused. What are the different scenarios when data collection is paused? Sorry if my questions are redundant. It would be of great help if you could point me to related issues/relevant documentation.

**Comment by shankari** [comment]
@MythriNagaraju yeah can you just file a new issue? Maybe with a subject like "How to skip the consent screen in the UI?" Would also be great if you could provide more details - e.g.
- how did you "marked consent in the code"
- what do you mean by "expects user consent to re-start data collection when data collection is paused"? How is data collection paused (tracking toggle/something else)?
