### ISSUE TITLE
Error loading aggregate data, averages not available

### ISSUE THREAD

**Issue by jf87** [e-mission/e-mission-docs#288]
I get that error every time when the app is open for the first time and after it has been killed.
I replaced the hard-coded e-mission url in metrics.js with my own server, but it does not seem to help.
What data is this supposed to get?
![img_6768](https://user-images.githubusercontent.com/2108882/51030664-6d098c80-159a-11e9-83ae-ac3b390b6382.PNG)

Thanks :-)

**Comment by jf87** [comment]
This is the issue I think.
The following post request returns just empty results.

`{"aggregate_metrics": [[], [], [], []]}`

`curl -XPOST --header "Content-Type: application/json" --data '{"freq":"D","start_time":1548633600,"end_time":1549756800,"metric_list":["duration","median_speed","count","distance"],"is_return_aggregate":true}' https://e-mission.eecs.berkeley.edu/result/metrics/timestamp  -w "\n%{time_connect} : %{time_starttransfer} : %{time_total}"
`
Plus there is an issue for your server. This request takes 110s to complete.
Any idea why it is empty and why it takes so long?

**Comment by shankari** [comment]
so I just created a new server (actually multiple new servers) while testing https://github.com/e-mission/e-mission-server/pull/637 and ) and I can't reproduce this even with only one user. I looked at the code, and the popup only occurs when the server returns an error.

```
      getAggMetricsFromServer().then(function(results) {
          ...              <- HTTP 200 OK, even with empty arrays
      })
      .catch(function(error) {  <- HTTP != 200
        $ionicLoading.hide();
        $scope.carbonData.aggrCarbon = "Unknown";
        $scope.caloriesData.aggrCalories = "Unknown...";
        $ionicPopup.alert({
          title: "Error loading aggregate data, averages not available",
          template: JSON.stringify(error)
        });
        console.log(error);
      });
   };
```

**Comment by shankari** [comment]
I also connected a debugger to the client and inserted a breakpoint in at the first line in the success block  (`$scope.fillAggregateValues(results.data.aggregate_metrics);`). The breakpoint was hit, even though the results were blank 

<img width="522" alt="screen shot 2019-02-12 at 4 59 08 pm" src="https://user-images.githubusercontent.com/2423263/52678747-a0b43b00-2ee7-11e9-8b42-1dff80124903.png">

comparing this to the error reported in https://github.com/e-mission/e-mission-docs/issues/288#issue-408958777 

it looks like the main difference is that:
1. in the working case: `data: {aggregate_metrics: [[], [], [], []]}`
1. in the error case: `data: null`

**Comment by shankari** [comment]
can you look at the server logs and see if there is anything there?

**Comment by shankari** [comment]
I also compared the status of the response.

In the working case

```
status: 200
statusText: "OK"
```

in the error case above

```
status: -1
statusText: ""
```

**Comment by shankari** [comment]
since the call is through the angular `$http` library, 

```
      var getMetricsResult = $http.post(
        "https://e-mission.eecs.berkeley.edu/result/metrics/timestamp",
        clonedData)
      return getMetricsResult;
```

we can look at the `$http` implementation
https://github.com/angular/angular.js/blob/6706353a71e3c11c56c0b19be03600dac57aafe1/src/ng/http.js#L907

according to the comments there, 

>      *   in the error callback being called.
>      *   Also, status codes less than -1 are normalized to zero. -1 usually means
>      *   the request was aborted, e.g. using a `config.timeout`. More information
>      *   about the status might be available in the `xhrStatus` property.
>      *

So could it just be that the call timed out while connecting to the server? Can you check the server logs to see whether it received a request at around the time of the error, and if so, what happened to it?

**Comment by shankari** [comment]
The error popup https://github.com/e-mission/e-mission-docs/issues/288#issuecomment-463014068 does not have an `xhrStatus` property ☹️ so "more information on the status" is not available

**Comment by jf87** [comment]
Server shows this:
START 2019-02-13 09:48:29.837809 POST /result/metrics/timestamp
END 2019-02-13 09:48:29.861343 POST /result/metrics/timestamp a21840aa-6687-4ab5-9ed1-xxxxxxxxx 0.02340316772460937

**Comment by jf87** [comment]
Ok. I found the reason:

`Refused to connect to https://myownserver.com because it violates the following Content Security Policy directive...`

It is necessary to adapt www/index.html of the cordova app in case of a separate server instance.

`
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com http://nominatim.openstreetmap.org https://myownserver.com https://api.ionic.io/push/tokens emission: 'unsafe-eval'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: http://*.tile.openstreetmap.org http://tile.stamen.com https://*.tile.stamen.com http://*.tile.stamen.com 'unsafe-inline'">
`

I guess `https://api.ionic.io/push/tokens emission` also needs to be changed in case I enable iOS push notifications?

It might be good to collect these places somewhere in the docs.
Or maybe git grep with some keywords will already help to figure out where to make adaptations?

**Comment by shankari** [comment]
aha! that's why I have only seen this periodically - most of the other groups that used their own servers turned off the aggregate code. TripAware might have been the only one that kept it.

> It might be good to collect these places somewhere in the docs.

It is in the docs, although maybe not in a very organized place 
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md

If you can add this information to the doc (and potentially rename it for clarity), it would be great!

**Comment by shankari** [comment]
> I guess `https://api.ionic.io/push/tokens emission` also needs to be changed in case I enable iOS push notifications?

Ionic is actually javascript framework on top of angular. We used to use them for push notifications, but now we use firebase, and the mapping happens all on the server side. So we should be able to remove `https://api.ionic.io/push/tokens` from that list.

**Comment by shankari** [comment]
Also, I have a longer-term question. 

**Background:** The reason that the aggregate call is affected by this while the user call is not is because `$http` is a javascript call and the user call goes through a native plugin. The native plugin is configured through the `connectionConfig.json` and so it can, by default, only call back to the server associated with the phone app.

And the reason that we used `$http` instead of the native plugin (among many reasons) is that the native plugin always sends the user token, and my original vision was that the aggregate data would always be public.

But now, we know that is not a good model for anything other than heatmaps, and even for heatmaps, you need to be careful. The new vision is to have an aggregator, and queries that authenticate themselves with the aggregator.

**Question:** (@jf87 @PatGendre) So should we start going towards this model by requiring authentication for the aggregate data as well? The effect would be that the aggregate data would only be visible to the community of contributors. So if I submit data, I can see aggregate data, otherwise I can't. This would not be a hard change, and it would also allow us to use the native plugin for all server calls.

Thoughts?

**Comment by shankari** [comment]
@deepalics0044 I think you ran into this when you set up your own server initially?

**Comment by jf87** [comment]
Yes. I think the better solution would be to use the native plugin.
Plus you can easily extend it to more fine-grained access models having authentication.
Access control should happen on the server side and the individual e-mission deployer should be able to decide if aggregate data is available publicly, only to participants or even only to specific users/on a specific granularity.

**Comment by shankari** [comment]
>  Access control should happen on the server side and the individual e-mission deployer should be able to decide if aggregate data is available publicly, only to participants or even only to specific users/on a specific granularity.

Will probably only implement the first two options (aggregate data is available publicly v/s only to participants) initially to avoid over-engineering. Will try to get to this after merging the GIS based mode detection.

**Comment by jf87** [comment]
> Will probably only implement the first two options (aggregate data is available publicly v/s only to participants) initially to avoid over-engineering. Will try to get to this after merging the GIS based mode detection.

Yes sure. I just wanted to hint that this option is flexible enough to implement various schemes :-)

**Comment by PatGendre** [comment]
I agree with Jonathan "Access control should happen on the server side and the individual e-mission deployer should be able to decide [how] aggregate data is available."
Also, aggregate data may be used in a completely separate app than personal data, e.g. it is not necessarily useful to request and display aggregate data for the smartphone app, it could be used in a desktop browser web GIS app.

**Comment by shankari** [comment]
I'm making some changes to the web interface, so decided to tackle some parts of this at the same time.

Quick response to @PatGendre wrt 
>  Also, aggregate data may be used in a completely separate app than personal data, e.g. it is not necessarily useful to request and display aggregate data for the smartphone app, it could be used in a desktop browser web GIS app.

This is already supported. Check out the "Analysis" or "Metrics" tabs on the existing web UI. And because the phone app uses HTML + javascript, we are able to largely re-use the same code on the phone and web apps. IIRC, the main differences are in the HTML, mainly because I am not very good at responsive UX.

In fact, the initial and current version (before my pending changes) was that user specific information would only be available through the phone app, and the aggregate information would be publicly available through both the phone and web apps.

**Comment by PatGendre** [comment]
@shankari : thanks! I'll be watching the improvements you are bringing to the web interface. The discussion above with Jonathan gets clearer to me now.

**Comment by PatGendre** [comment]
@shankari 
Hi , I still have this "Error loading aggregate data, averages not available" error on the dashboard.
We I do a the request corresponding to this error in the phone log `curl -XPOST --header "Content-Type: application/json" --data '{"freq":"D","start_time":1557705600,"end_time":1558828800,"metric_list":["duration","median_speed","count","distance"],"is_return_aggregate":true}' https://fabmob.grfmap.com:8080/result/metrics/timestamp -w "\n%{time_connect} : %{time_starttransfer} : %{time_total}\n" 
`
The returned data is neither `null` nor `{aggregate_metrics: [[], [], [], []]}`.

**Comment by PatGendre** [comment]
As discussed yesterday our problem is not related to the need to adapt the www/index.html of the cordova app in case of a separate server instance. (in <meta http-equiv="Content-Security-Policy" ).
It was related to a webserver conf, that we solved.
By the way this issue can be closed ? As it has been solved and [described in the docs](https://github.com/e-mission/e-mission-docs/pull/317).

**Comment by shankari** [comment]
Sure. I left it open for the long-term issue, but I guess we can file a new issue for that.
