### ISSUE TITLE
See if the tracking is on

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#323]
when using the app with the location not activated, how can the user know that the tracking is off and be reminded he/she should activate location tracking? (at least for older android versions, there is no indication clearly visible) 
Does the tracking work even if the data connection is off?

**Comment by shankari** [comment]
there used to be a notification generated every time there was a state transition
e.g.

https://github.com/e-mission/e-mission-data-collection/blob/master/src/android/location/TripDiaryStateMachineService.java#L299

https://github.com/e-mission/e-mission-data-collection/blob/master/src/android/location/TripDiaryStateMachineService.java#L371

However, my advisors hated it, so I added a check for `isSimulateUserInteraction`. You can set that as part of the sensing config and it will generate the notifications.

As part of the fixes for https://github.com/e-mission/e-mission-data-collection/issues/127 there is now a new notification if LocationServices are turned off, on all android versions. and if you click on the notification, it should prompt you to re-enable location services. And if the user dismisses the prompt, it should be re-generated when the periodic timer goes off (~ every hour, but may change depending on phone usage when Doze mode is enabled).

**Comment by shankari** [comment]
Finally, if the version is Oreo+ and the state is ONGOING_TRIP_STATE, we generate a notification through a foreground service. 
https://github.com/e-mission/e-mission-data-collection/blob/master/src/android/location/TripDiaryStateMachineForegroundService.java#L35

We enabled this only for Oreo+ because it is required only for that (https://github.com/e-mission/e-mission-data-collection/issues/164#issuecomment-361741749), and we felt like having it for all versions would creep people out unnessarily. But we haven't done any rigorous user tests on that; would love to get your feedback on it, specially if it includes user feedback.

**Comment by shankari** [comment]
Please let me know if you have more questions.

**Comment by shankari** [comment]
I think there are many ways of implementing this; I am just not sure which is best from a UX perspective. I am not a UX expert, and the whole point of making e-mission a platform was to allow UX experts to figure this stuff out without having to deal with the details of the sensing. 

So I am definitely open to inputs in this regard

**Comment by PatGendre** [comment]
Thanks! I have changed simulate_user_interaction to true, and switched off location tracking, but for the moment I don't see any notification (but I am in my hotel room so I don't move, I will try again).

Besides, I have seen that emission is running in the background when I close the app, because I have regularly an "Error 1000 when creating geofence" message which seem to be caused by the absence of location tracking. Like I think other users, I switched off quite routinely the location and the mobile data when I don't use the phone (i.e. when I just use it as a phone, not a smartphone). I think if I answer "snooze" to the alert I won't be bothered by the geofence error another time, right?

I am not an UX expert, but I believe a sizeable proportion of users may also switch off location regularly, so the app should be able to manage it smoothly. By allowing to turn off geofence errors (in the user profile maybe), and possible by having a small location logo or barred location logo (when it is off) always visible somewhere in the upper right corner for instance?

**Comment by shankari** [comment]
@PatGendre are you using the version uploaded to https://github.com/e-mission/e-mission-data-collection/issues/127 That should have the fixes for turning location on/off.

Yes, if the geofence is not created, as part of the periodic operations (~ 1 hour, maybe longer in doze mode), we will generate a notification. if you use the version with the fixes from https://github.com/e-mission/e-mission-data-collection/issues/127 it may show a different error "Error 6" instead of "Error 1000" but it will show some notification.

I did not test with snoozing the notification; let me know what you find when you test it.

**Comment by shankari** [comment]
> By allowing to turn off geofence errors (in the user profile maybe), and possible by having a small location logo or barred location logo (when it is off) always visible somewhere in the upper right corner for instance?

Isn't this already done by the android OS?

**Comment by PatGendre** [comment]
i could not install the fix now, connection is quite slow, i'll check
tomorrow and tell you.

**Comment by PatGendre** [comment]
The fix of issue #127 (although not tested for a long time) seems to fix the problem, thank you, I close the issue, and let the UI design improvements mature...
