### ISSUE TITLE
No module named future

### ISSUE THREAD

**Issue by hmharvey** [e-mission/e-mission-docs#327]
When trying to use the ipython notebook, I'm running into an Import error: No module named future. This was mentioned in a previous issue but didn't have a solution.

**Comment by shankari** [comment]
This happens if you are using a manual (as opposed to docker) install but are NOT in the emission environment.

If you are using a manual install, you *must* switch to the emission environment before you run any emission code
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/manual_install.md

> Verify that you are in the right environment - your prompt should start with (emission) and the emission environment should be starred.

**Comment by shankari** [comment]
Updated the manual install documentation to also clarify that `source activate emission` also works to switch to the new environment after it it set up using `source setup/setup.sh` Closing this issue now.
