### ISSUE TITLE
the delete_user script is not working

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#338]
the [bin/delete_user.py](https://github.com/e-mission/e-mission-server/blob/master/bin/delete_user.py) script doesn't work, because in  `from get_database import get_uuid_db, get_profile_db, get_moves_db`, the path should be emission.core.get_dabase, but then the get_moves_db doesn't exist in get_database.
Is this script obsolete? 
Also, it is based on user e-mail, but what if we have 2 users with the same e-mail in the DB, for whatever reason ? (this is possible as no check is made on the unique e-mail when registering, currently).

More generally, the scripts in the /bin directory seem quite useful but are some of them obsolete? Is it possible to check which scripts are still reliable in the current codebase?
Thanks in advance

**Comment by shankari** [comment]
Ok, so I went through my stashed changes, and this is the one that I had pending 
https://github.com/e-mission/e-mission-server/pull/578/commits/a374683270d14f36ca9f776b1d9ae9d58816ef67

Unfortunately, I think that the one it fixed was `purge_multi_timeline_for_range.py`, not `delete_user.py. Fixing `delete_user.py` now...

**Comment by shankari** [comment]
Responding to the other questions:

>  Also, it is based on user e-mail, but what if we have 2 users with the same e-mail in the DB, for whatever reason ? (this is possible as no check is made on the unique e-mail when registering, currently).

This is not true. The registration server code does check for unique email and updates instead of creates if an entry is already present.
https://github.com/e-mission/e-mission-server/blob/master/emission/core/wrapper/user.py#L154

> More generally, the scripts in the /bin directory seem quite useful but are some of them obsolete? Is it possible to check which scripts are still reliable in the current codebase?

It is possible that some are obsolete. Everything in `bin/historical` was effectively written for a one-time fix of some data and is definitely not guaranteed to be current. For the others, I just fix them as I run into broken scripts. 

In general, I changed the data model significantly once, back in Sep 2015, but haven't changed it since then. 

So any scripts that have not been changed substantially since then are obsolete. `delete_user.py` was last changed in Jul 2015 - the later changes were automated and related to the `python2` -> `python3` migration.

**Comment by shankari** [comment]
Fixed by https://github.com/e-mission/e-mission-server/pull/641
