### ISSUE TITLE
Changing the UI client_setup.html page

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-docs#348]
I have been trying to change the client_setup.html page on the server. The page remains the same.
[http://emission.cistup.iisc.ac.in:8080/#/client_setup?new_client=cistupec&clear_usercache=true&clear_local_storage=true](url)

Changed locations
`/home/deepali/e-mission-server/webapp/e-mission-server/webapp/www/templates/client_setup.html`

`/home/deepali/e-mission-server/webapp/www/templates/client_setup.html`

What I found out that there should be a change from your end.

**Comment by shankari** [comment]
there definitely does not have to be a change from my end. The tripaware study changed the landing page for their copy of the server completely without any change to the main branch.

`/home/deepali/e-mission-server/webapp/www/templates/client_setup.html` **is** the file to change.
What change did you try to make? And how do you know that it does not work?

I am not sure how you have a file
`/home/deepali/e-mission-server/webapp/e-mission-server/webapp/www/templates/client_setup.html` since there is no `e-mission-server` directory in `webapp`.
https://github.com/e-mission/e-mission-server/tree/master/webapp

**Comment by shankari** [comment]
I just checked the URL and the page is clearly different from the one on master

<img width="1315" alt="Screen Shot 2019-03-25 at 7 41 13 AM" src="https://user-images.githubusercontent.com/2423263/54928636-733cb300-4ed1-11e9-9bcf-ab925a03aa35.png">
