### ISSUE TITLE
Retrieve the date when the user installed and uninstalled  the application

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-docs#352]
Does the e-mission supports application install and uninstall dates? Its obvious that the installation date is the day when the uuid gets generated.Can we get dates next to uuid? Where could we get the dates when the users installed, and uninstalled (if any)?

**Comment by shankari** [comment]
@deepalics0044 no e-mission does not track uninstall dates, notably because it cannot
e.g. https://stackoverflow.com/questions/2874412/get-application-uninstall-event-in-android
You would need to infer this from the data.

For the TRB paper, I used the incidence of `/usercache/put` to determine when the app stopped periodically connecting the server (https://doi.org/10.1177%2F0361198118770167). As you can see from the paper, the notebook used to generate the evaluation is here (https://github.com/e-mission/e-mission-eval/blob/master/emission_overview_trb_2017/app_usage_metrics.ipynb)

**Comment by shankari** [comment]
Link to source documentation about uninstall just for reference
https://developer.android.com/reference/android/content/Intent.html#ACTION_PACKAGE_REMOVED
