### ISSUE TITLE
Each time asks for update in IOS

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-docs#359]
Whenever I open emTripLog, it asks for UI update even when there are no updates made in the channel. This behaviour happen in one iOS phone only. Sending you the log .

**Comment by shankari** [comment]
@deepalics0044 can you update the rough date and time at which you opened emTripLog and were prompted for the UI update? Because here's what I see from the logs that you sent me offline.

#### Exporting the logs to human readable format... ####

```
(emission) e-mission-phone$ python bin/csv_export_add_date.py /tmp/loggerDB.ipsita_always_prompts
exporting csv to /tmp/loggerDB.ipsita_always_prompts.csv
adding dates to the dataframe
exporting csv with date to /tmp/loggerDB.ipsita_always_prompts.withdate.log
```

#### When the user accepted the update ####

```
$ grep "Ionic Deploy: User accepted" /tmp/loggerDB.ipsita_always_prompts.withdate.log
51,1553734133.9186301,2019-03-27 17:48:53.918630-07:53,Ionic Deploy: User accepted deploy update
8519,1553768523.46475,2019-03-28 03:22:03.464750-07:53,Ionic Deploy: User accepted deploy update
15616,1554344409.52613,2019-04-03 19:20:09.526130-07:53,Ionic Deploy: User accepted deploy update
```

#### When the last UI updates happened ####

Looking at the commits to the `cistup-ec` branch
https://github.com/e-mission/e-mission-phone/commits/cistup-ec
there were multiple updates on the 27th PDT, notably to the fit and finish (https://github.com/e-mission/e-mission-phone/pull/542) and the consent (https://github.com/e-mission/e-mission-phone/pull/543)

#### What happened after each of the accepts ####
##### 27th March: Update was successful #####
```
51,1553734133.9186301,2019-03-27 17:48:53.918630-07:53,Ionic Deploy: User accepted deploy|~
 update
52,1553734141.07178,2019-03-27 17:49:01.071780-07:53,Ionic Deploy: Update Success! done
```

##### Commits happened here #####

##### 28th March: Update was unsuccessful ####
probably because the application was sent to the background without waiting for the update to complete
```
8519,1553768523.46475,2019-03-28 03:22:03.464750-07:53,Ionic Deploy: User accepted deploy
 update
8520,1553768571.79471,2019-03-28 03:22:51.794710-07:53,Application went to the background
```

##### 3rd Apr: Update was finally successful ####
this issue was filed at this time

```
15616,1554344409.52613,2019-04-03 19:20:09.526130-07:53,Ionic Deploy: User accepted deploy update                                                                                 |~
15617,1554344415.21303,2019-04-03 19:20:15.213030-07:53,Ionic Deploy: Update Success! done
```

##### 3rd Apr: No update required #####
The app was apparently re-launched fairly soon after the successful update, presumably to send the logs. This time, there was no pending update.

```
15690,1554344417.9833698,2019-04-03 19:20:17.983370-07:53,Ionic Deploy: Update available: false
```

and I would not have expected to see another prompt when emailing me the log

**Comment by shankari** [comment]
To summarize, I don't see any bug here.

If the app is sent to the background when the UI update is downloading, the download can fail, and the app will not be updated. The update is only complete when you see the "Update done, reloading..." message. If an update is not complete, you will be prompted for it the next time you launch the app.

Now that the last set of updates were applied on 3rd Apr, and there have been no updates for a while, I would expect that you will not get any further prompts while launching the app.

Please re-open if this is not the case, or if the reconstruction in https://github.com/e-mission/e-mission-docs/issues/359#issuecomment-480726812 is inaccurate. In the second case, please provide approximate date/times when you opened the app and saw the update prompt but are not listed here.
