### ISSUE TITLE
How to skip consent screen in UI

### ISSUE THREAD

**Issue by MythriNagaraju** [e-mission/e-mission-docs#360]
Is there a way to completely skip the consent process in the UI? The approach that I tried was to just force the markConsented() method to always return True, which worked fine until the user logs in.  But when data collection pauses, it asks user to re-consent. So it clearly looks for consent in the local storage. How do I get around this? 

Also, why does data collection pause every now and then? the iOS app also stops/crashes often , which I am guessing is because of the consent not getting handled properly.

![data_collection_paused](https://user-images.githubusercontent.com/1181774/55582854-570cf300-56d5-11e9-88af-547ac1c9c29f.png)

**Comment by shankari** [comment]
@MythriNagaraju the notion of consent is fundamental to the whole data collection module and FSM. The consent is stored, both locally and remotely and is checked on every initialization to confirm that the data collection terms have not yet changed.

If you really want to remove it (which I don't recommend), you had the right idea with `markConsented()`, but it is not enough to have it return true (in fact, it always returns true now, so I am not sure what you mean).

```
        } else if (action.equals("markConsented")) {
            Log.d(cordova.getActivity(), TAG, "marking consent as done");
...
            callbackContext.success();
            return true;
```

The most supported option, the only one that does not require native code changes, and the one I would recommend if you really want to do this, is to just call `markConsented`  from the javascript UI. This doesn't **have** to be from a consent screen. For example, you can trigger the `markConsented` from the summary screen instead of the consent screen (which you have now removed). Or after the user has logged in. Or ????

Alternatively, since you are building your own native UI, you can override `ConfigManager.isConsented` to always return true. That should work, but has never been tested. If you choose to follow that route, you need to test it yourself and report any issues that you encounter. I will put some effort towards helping you in this case, but might not be able to do too much since this is not part of the core functionality any more.

**Comment by shankari** [comment]
For the record, the notification with "collection paused until consent" is generated if the intro is done but there is no stored consent.

https://github.com/e-mission/e-mission-data-collection/blob/master/src/android/location/TripDiaryStateMachineReceiver.java#L105

**Comment by MythriNagaraju** [comment]
That clears up a lot of things. Thanks @shankari !

**Comment by shankari** [comment]
@MythriNagaraju do you still have questions, or can we resolve this issue?

**Comment by MythriNagaraju** [comment]
@shankari : We are planning to keep the consent screen (modified for our client). That seemed like the easiest, cleanest way to go about it. Thanks for all your help!

**Comment by shankari** [comment]
@MythriNagaraju great! I will close this issue then. Given that location data is so sensitive, I feel strongly that users should know upfront that the app will collect it. But I definitely intended each deployment to customize the screen to its own needs.
