### ISSUE TITLE
Carbon calculations on phone

### ISSUE THREAD

**Issue by tms-martins** [e-mission/e-mission-docs#396]
It seems that the carbon calculations are not happening on the phone. Footprint is always 0 and Average always "calculating". This also happens when using a server with mode estimation enabled.

**Comment by shankari** [comment]
Ah, this one is easy. I put a breakpoint in `$scope.fillFootprintCardUserVals` and it was obvious :)
On the phone, we only calculate the carbon footprint if it is `IN_VEHICLE` but with the GIS-based mode inference, we actually have `CAR`, `BUS`, `TRAIN`, not `IN_VEHICLE`, so the values are never calculated :)

```
          if (userCarbonData[i].key === "IN_VEHICLE") {
            $scope.carbonData.userCarbon = FootprintHelper.getFootprint(userCarbonData[i].values, userCarbonData[i].key);
            $scope.carbonData.optimalCarbon = FootprintHelper.getFootprint(optimalDistance, userCarbonData[i].key);
            $scope.carbonData.worstCarbon = FootprintHelper.getFootprint(worstDistance, userCarbonData[i].key);
            lastWeekCarbonInt = FootprintHelper.getFootprintRaw(userCarbonData[i].values, userCarbonData[i].key);
          }
```

```
> userCarbonData
< [{key: "CAR", values: 231265}, {key: "ON_FOOT", values: 3715}] (2)
```

**Comment by shankari** [comment]
Note also that the GIS based mode inference can technically distinguish between transit modes (https://github.com/e-mission/e-mission-server/pull/578/files#diff-b64a9eb8dbe2ce052d4a1779485f7abdR180)

I collapse them to `BUS` and `TRAIN` because that is what the UI supports. But technically, you could return the richer modes, and get a better estimate of the carbon footprint.

**Comment by tms-martins** [comment]
I'm working on a branch in my fork, to have the carbon footprints calculated based on vehicle categories from GIS data; that is, it should support the modes "CAR", "TRAIN" and "BUS" (at least) instead of the aggregate "IN_VEHICLE"

**Comment by tms-martins** [comment]
In [file metrics.js, function fillFootprintCardUserVals()](https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js#L711)
You are using `IN_VEHICLE` as an aggregate of vehicle modes, and calling `FootprintHelper.getFootprintRaw()`, which returns an array with 2 values (for car and train), instead of a single value.

1. why wasn't bus included in `getFootprintRaw()` - only car and train?
2. is this behavior to be kept for some reason; or can I instead provide a single number for the footprint, based on a single mode of transportation (walking, cycling, bus, car, train and plane) in `getFootprintRaw()` and `getFootprint()`?

**Comment by shankari** [comment]
@tms-martins looking back at the history, the change was committed in
https://github.com/e-mission/e-mission-phone/commit/353916b4355b60c99f657e766da7bc985e6bd291

and the code at that time makes it more clear what we were trying to do

```
               $scope.carbonData.userVehicleRange = FootprintHelper.getFootprintRaw(userCarbonData[i].values, userCarbonData[i].key); 
```

Basically, since we didn't know what the actual mode was, we calculated a range of carbon footprints for vehicular modes from lowest (train) to highest (car).

This is the related issue and has more detail if you are interested
https://github.com/e-mission/e-mission-docs/issues/139

Now that we have an actual estimate of the mode, we don't have return a range any more, you can indeed provide a single number for the footprint.

**Comment by tms-martins** [comment]
A couple more questions (in `metrics.js`):
1. I see scope variables being set inside for-loops, e.g. in [line 708](https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js#L708); I would assume every iteration overwrites the previous value, instead of adding up (which was perhaps intended). Am I missing something?
2. in `getUserMetricsFromServer` [line 405](https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js#L405) metrics are obtained using `CommHelper.getMetrics(theMode, clonedData)`; however in `getAggMetricsFromServer` (immediately below) there is a hard-coded URL for the server. Why is this so?

**Comment by shankari** [comment]
@tms-martins 
2. https://github.com/e-mission/e-mission-docs/issues/288#issuecomment-463451604
1. The `userCarbonData` is grouped by mode, so we only expect one entry with `key === IN_VEHICLE`. The for loop is basically to find the `IN_VEHICLE` entry, since initially that was the only one that contributed to the carbon emissions. Should be fine to add up now that the modes are separated.

**Comment by tms-martins** [comment]
Thank you @shankari :)

**Comment by tms-martins** [comment]
@shankari: In order to calculate the optimal and worse carbon footprints, both the [optimal and worst distances are calculated](https://github.com/e-mission/e-mission-phone/blob/11734545c7b9283beeb72c63899763091363ae98/www/js/metrics.js#L695). If I have multiple modes (i.e. CAR, TRAIN, BUS, AIR_OR_HSR), which carbon emission value should I use - e.g. do I average them, use the best/worst? Or should the optimal and worst footprints be calculated differently?

**Comment by tms-martins** [comment]
Also, I just pushed the work-in-progress: branch [update_carbon_calc_for_GIS](https://github.com/tms-martins/e-mission-phone/tree/update_carbon_calc_for_GIS)

**Comment by shankari** [comment]
@tms-martins my thought was that for the optimal, you would use the lowest emission value mode (typically `TRAIN`) and for the worst, the highest (typically `CAR`).

The idea behind the optimal number is to address the concern that people have about their constraints - e.g. "I live 50km from my work; I have to drive". So the optimal value will tell you the best that you can do with your travel constraints - if you used walk/bike for all short trips and train for all long trips, this is as low as you can go.

The idea behind the worst number is to make people who are making an effort feel good. Although I have a non-zero carbon footprint, I am making a difference by choosing public transit. If I drove everywhere, it would be so much worse.

**Comment by shankari** [comment]
> Also, I just pushed the work-in-progress

You can actually create a draft PR off the branch and get incremental reviews when you are ready.

**Comment by tms-martins** [comment]
@shankari I created the [PR for the feature](https://github.com/e-mission/e-mission-phone/pull/576). There are a couple of outstanding issues (see PR description) and I still have to clean-up comments and a couple of test settings. Feedback is welcome ⭐️ 
At this stage I can already advance with [locale-specific carbon footprints](https://github.com/e-mission/e-mission-docs/issues/399)

**Comment by tms-martins** [comment]
Hopefully this was solved by [PR 576](https://github.com/e-mission/e-mission-phone/pull/576) which is now merged. 😌
