### ISSUE TITLE
Cleaning and resampling stage fails

### ISSUE THREAD

**Issue by jf87** [e-mission/e-mission-docs#400]
Hi Shankari,

I have some weird behavior, which you might be able to resolve quickly.
If not I will dig more into it myself.

I am doing some tests and have therefore exported data from myself for a single day using your script:

`extract_timeline_for_day_range_and_user.py "2019-05-14" "2019-05-15" "./" -u fe8e561f-0676-44f8-aeb6-300606be5682`

Then I load this data into a new user, again using your script:

`load_timeline_for_day_and_user.py`

This all works fine. However, when I then try and run the intake pipeline for this new user `/intake_single_user.py -e test-user`, the pipeline fails in the cleaning & resampling phase. The reason is that `get_entry_at_ts` returns None.

`2019-05-14 17:56:47,668:DEBUG:4532909504:get_entry_at_ts query = {'user_id': UUID('7d105611-4d7c-430d-b970-3a37f8d56903'), 'metadata.key': 'background/filtered_location', 'data.ts': 1554745162.9978106}

2019-05-14 17:56:47,670:DEBUG:4532909504:get_entry_at_ts result = None
`
`get_entry_at_ts` is called from `emission/analysis/intake/cleaning/clean_and_resample.py:695`:
`        raw_start_place_enter_loc_entry = ecwe.Entry(
            ts.get_entry_at_ts("background/filtered_location", "data.ts",
                               raw_place.data.enter_ts))
`
If I load some sample data from you, the pipeline runs smoothly.
Also, if I use a clean mongodb instance and just load the data, the same problem occurs.
For the original data (before the export) the pipeline runs smoothly as well.

Any ideas? Thanks :-)

**Comment by shankari** [comment]
@jf87 I suspect this is because `extract_timeline_for_day_range_and_user.py` pulls the analysis timeseries data in addition to the raw timeseries data. So it looks like you got the start place, and not the location at which you entered that start place because it was from the previous day.

Quick check to see if this is true:
- check the timestamp that you are trying to retrieve the entry for - is it from the previous day?

Quick resolutions (which also provide confirmation that this is the issue):
- reset the pipeline (bin/reset_pipeline.py). This will delete all downloaded analysed data, so when you re-run the pipeline, it will create a starting place with no `enter_ts` (since this is the beginning of known time) and everything will work
- if you want data for a single user, extract data using `extract_timeline_for_day_and_user` which only extracts the raw data, not the analysed results

In general, I use `extract_timeline_for_day_range_and_user` to dump data for a long time and multiple users - e.g. to extract data for the Paraguay study that used my server.

**Comment by jf87** [comment]
Thanks a lot. Just as an intermediate feedback. This already helped:

> if you want data for a single user, extract data using extract_timeline_for_day_and_user which only extracts the raw data, not the analysed results

**Comment by shankari** [comment]
ok, closing this issue then...
