### ISSUE TITLE
explain tracking settings during onboarding

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#407]
We have tested our iOS app, and we have this "error while reading activities  / travel mode detection may be unavailable" : the exception comes from the data collection plugin, it seems to be an iOS specific issue (the exception is found only in the ios native code).
We believe this is because as we are lauching the app for the first time, we have been not yet asked for permission to use phone location, and that this message will not be displayed anymore once we have accepted to use phone location data. Is it correct?

Another question related to permissions on iOS : we have the choice of accepting to access phone location even when the app is in the background or only when the app is launched. How does the app behave if we accept only the latter?

Even on Android (sorry we did not test it), is the app still usable if we do not give permission to access the phone location? (or if later on we decide to remove this permission in the app parameters). 
Can the user see easily if she/he refused inadvertently to give the permission, so that she/he may change the permission?

**Comment by shankari** [comment]
> error while reading activities / travel mode detection may be unavailable

This is generated on some old iPhones (e.g. iPhone 5s-) that do not have the M7 coprocessor and do not support the on phone motion activity detection. It is also generated on the emulator, IIRC. It should not appear on any reasonably modern iPhone (iPhone 6+)

> Another question related to permissions on iOS : we have the choice of accepting to access phone location even when the app is in the background or only when the app is launched. How does the app behave if we accept only the latter?

It will not work. We need background access, otherwise, we cannot track location in the background. Previous groups have highlighted this on their install pages, but ideally we would highlight it as part of onboarding...
https://github.com/e-mission/e-mission-base/blob/master/www/templates/about-app.html#L18

> Even on Android (sorry we did not test it), is the app still usable if we do not give permission to access the phone location? (or if later on we decide to remove this permission in the app parameters).
> Can the user see easily if she/he refused inadvertently to give the permission, so that she/he may change the permission?

On android, there is a notification generated roughly every hour if the location permissions are turned off (similar to location services being turned off).
