### ISSUE TITLE
Issue with storing selected destination (CommHelper.putOne not a function)

### ISSUE THREAD

**Issue by trevor-wu** [e-mission/e-mission-docs#411]
<img width="785" alt="Screen Shot 2019-06-09 at 2 54 22 AM" src="https://user-images.githubusercontent.com/35517530/59157624-956eb780-8a62-11e9-9581-cee21467fc5e.png">
When I select a destination from the dropdown menu, it pops up with the error above. As a result, the selection is not stored and the trip details page breaks when trying to access $scope.tripgj.usermode.value
![Uploading Screen Shot 2019-06-09 at 3.01.52 AM.png…]()

**Comment by trevor-wu** [comment]
This is from e-mission-phone greentrip branch.

**Comment by shankari** [comment]
@trevor-wu is this from the channel or from your checked out repository?
If the channel works, but your repository doesn't, there must be an issue with your code.
As an obvious check, have you tried to pull from master?

I have checked in all my code, but I did not guarantee that you have to do zero work.
you might want to look at the PRs that I linked to so that you can understand the changes in isolation.

**Comment by shankari** [comment]
But thanks for filing a issue instead of sending email! 👍 😃

**Comment by shankari** [comment]
@trevor-wu if you were able to resolve this, could you document the resolution and close the issue?

**Comment by shankari** [comment]
Closing this since there have been no updates from @trevor-wu for a while
