### ISSUE TITLE
cannot load user data in dashboard (metrics screen)

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#414]
After filling the user info  ("calibrate" button for the Calories computation) : size, gender, height, age, the dashboard displays an error (see screenshot)
![cannot-load-userdata](https://user-images.githubusercontent.com/5039447/59272079-7d12be80-8c55-11e9-8104-2c5bb8a8368a.png)

Because of this error, no metrics are displayed.

The error disappears if I erase user data (in Profile / Dev zone / User data) and start the app again.

**Comment by DO3B** [comment]
https://github.com/e-mission/e-mission-phone/blob/f03c1fff43933141c33eb1723e501f871ffaad94/www/js/metrics.js#L680 

After some research, `storedUserData` is never declared in the `$scope`. I guess it should be `savedUserData`.

**Comment by shankari** [comment]
Yup. and looking at the blame, it looks like I changed it when I switched a bunch of stored variables to native storage instead of web local storage in order to fix issues with values disappearing on iOS
https://github.com/e-mission/e-mission-phone/pull/470

in

https://github.com/e-mission/e-mission-phone/commit/a99c4e8798b7cfa71db5b366c73bbf4f5f2f0237

Apparently, as part of the testing done, I did 

> - Set the user information in the dashboard - verified that it was visible in the profile

But I didn't verify the actual calculations that used the dashboard information had the right variable.
Sorry about that - do you want me to fix it, or do you want to submit another PR?

**Comment by DO3B** [comment]
I think, it is better if you are fixing it. A PR seems a bit too much for a small change :)
