### ISSUE TITLE
"Today" button in trip diary's date selector isn't working

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#432]
Not sure if this problem is exclusively to rk-unsw branch or not. Does it work on other branches?

**Comment by shankari** [comment]
This is a bug in the datepicker library that we use (https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/300). That issue describes a fix; let me see if applying that fixes it.

**Comment by shankari** [comment]
The fixes to the master branch of the datepicker library work, but there has been no release since Sept 2016, so the changes are not in any dist file. The same issue pointed to a fork that had supposedly fixed the issue and had a recent distfile, but on testing, it looked like it is not actually working for our use case https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/300#issuecomment-518495623

So I am checking in a manually generated distfile for now while waiting for the others to respond on the issue in the library.

**Comment by shankari** [comment]
@asiripanich you need to merge this fix to your branch. You might also want to merge 
https://github.com/e-mission/e-mission-phone/pull/596
at the same time :)
