### ISSUE TITLE
a security warning for the Android app

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#464]
@shankari 
FYI we have a security warning in the Google Play Console.  It concerns angular, do you think this may be serious? (.i.e. Google could prevent us from publishing the app the near future?)

```
(my translation)
Your app contains at least one app with known security issues. Please see this article : https://support.google.com/faqs/answer/9464300 from Google help center.
Vulnerable JavaScript libs :
Name | Version | Known issues | Identified files
-- | -- | -- | --
angular.js | 1.4.14 | SNYK-npm:angular:20150807SNYK-npm:angular:20150909SNYK-npm:angular:20150310SNYK-npm:angular:20171018SNYK-npm:angular:20180202 | assets/www/lib/angular-cookies/angular-cookies.min.jsassets/www/lib/angular-cookies/angular-cookies.js
  | 1.4.3 | SNYK-npm:angular:20150807SNYK-npm:angular:20150909SNYK-npm:angular:20150310SNYK-npm:angular:20171018SNYK-npm:angular:20180202 | assets/www/lib/ionic/js/angular/angular-sanitize.jsassets/www/lib/ionic/js/angular/angular-sanitize.min.jsassets/www/lib/ionic/js/angular/angular.jsassets/www/lib/ionic/js/angular/angular-animate.min.jsassets/www/lib/ionic/js/angular/angular-resource.jsassets/www/lib/ionic/js/angular/angular-animate.jsassets/www/lib/ionic/js/angular/angular-resource.min.jsassets/www/lib/ionic/js/angular/angular.min.js
  | 1.5.3   ...
```

**Comment by shankari** [comment]
@PatGendre where are you seeing this warning? I haven't received any emails about this.

**Comment by shankari** [comment]
out of the two angular sub-packages listed there

`angular-sanitize.js` is included by ionic

```
├─┬ ionic#1.3.1 (latest is 1.3.5)
│ ├── angular#1.5.3 (latest is 1.7.8)
│ ├─┬ angular-animate#1.5.3 (latest is 1.7.8)
│ │ └── angular#1.5.3
│ ├─┬ angular-sanitize#1.5.3 (latest is 1.7.8)
│ │ └── angular#1.5.3
│ └─┬ angular-ui-router#0.2.13 (latest is 1.0.23)
│   └── angular#1.5.3 (1.7.8 available)
```

angular cookies is included by `angularLocalStorage`. I have already migrated away from `angularLocalStorage` to store data in the SQLite database, although I still use it to store UI-only state (e.g. has the user gone through the walkthrough) because you can access the state directly without using a promise. It should not be hard to migrate the rest of them and remove this dependency.

```
├─┬ angularLocalStorage#0.3.2
│ ├── angular#1.5.3 incompatible with ~1.4.7 (1.4.14 available, latest is 1.7.8)
│ └─┬ angular-cookies#1.4.14 (latest is 1.7.8)
│   └── angular#1.5.3 incompatible with 1.4.14 (1.4.14 available, latest is 1.7.8)
```

But I am not sure why local storage or cookies are a security issue. They could be a security issue if you store sensitive information (e.g. passwords) in them. But I've been pretty careful not to do that.

**Comment by shankari** [comment]
I don't see any security warnings for sanitize, which is part of the core angular library
https://docs.angularjs.org/api/ngSanitize/service/$sanitize
and angular is from google, so I am not quite sure what is going on.

<img width="526" alt="Screen Shot 2019-10-15 at 8 55 04 AM" src="https://user-images.githubusercontent.com/2423263/66848203-7fe62e80-ef29-11e9-839e-616609289acd.png">

**Comment by PatGendre** [comment]
@shankari 

> where are you seeing this warning? I haven't received any emails about this.
in the Google Play console

**Comment by PatGendre** [comment]
![alert-GPS-scrshot](https://user-images.githubusercontent.com/5039447/66848529-8bf7dd80-ef75-11e9-8f68-dfac3054854d.png)

**Comment by shankari** [comment]
ok I see the same message in my console. BUT I only see it for emTripLog, not e-mission.

**Comment by shankari** [comment]
And my alerts are only for angular-cookies and jquery. I wonder if the sanitize dependency was due to the i18n changes; I have not updated the deployed apps since the i18n changes, although you have.

<img width="1346" alt="Screen Shot 2019-10-15 at 9 04 43 AM" src="https://user-images.githubusercontent.com/2423263/66848949-dacc5580-ef2a-11e9-8aba-ba8b2a0d235d.png">

**Comment by shankari** [comment]
I can update the `angularLocalStorage` version (which is the simple fix) or if that doesn't work, remove the dependency. That should fix both the cookies and the jquery alerts in emTripLog.

sanitize will require more work.

**Comment by PatGendre** [comment]
you are right, this may be the reason, the i18n update.

**Comment by shankari** [comment]
Actually, I take that back. although there is no explicit dependency added by `angular-translate` that is because the dependency already existed.

`angular-translate` does depend on `angular-sanitize`
https://github.com/angular-translate/angular-translate/blob/aafbc39f6e22dba3a27652c24ddb1be1eb266985/bower.json#L17

**Comment by PatGendre** [comment]
Ok, so that might more difficult to remove the dependency.
Anyway I suppose this warning is not really critical so not urgent?

**Comment by shankari** [comment]
So according to the related Google Help Center article
https://support.google.com/faqs/answer/9464300

> This information is intended for developers with app(s) that contain one or more Java or JavaScript libraries with known security issues (e.g., common vulnerabilities and exposures - CVEs). Although unintended by the app developer, including such vulnerable libraries in an app can put app users at risk. A list of detected unsafe libraries and their locations can be found in the Play Console notification for your app.

However, when I search the CVE repository directly, https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=angular the only match related to angular-sanitize is for `textAngular-sanitize.js` which we don't use.

Would you have the time to file a stackoverflow post and ask them which CVE they refer to?

> If you have technical questions about the vulnerability, you can post to Stack Overflow and use the tag “android-security.”

**Comment by shankari** [comment]
I also don't see a CVE for `angular-cookies` and `angularLocalStorage` has not updated their dependency.
https://github.com/agrublev/angularLocalStorage/blob/master/bower.json#L16

Maybe ask for both and let's see what they say.

**Comment by shankari** [comment]
Just filed SO question; let's see if they respond
https://stackoverflow.com/questions/58400284/angular-sanitize-and-angular-cookies-cve-warnings-in-google-play-console

**Comment by shankari** [comment]
the question on SO has not yet been answered. So I assume that this is a false positive. If it is not answered by the end of this calendar year, I plan to close this issue.

**Comment by shankari** [comment]
closing now due to lack of response

**Comment by venu198** [comment]
Can you help me what's the issue is this. Really thanks to one who helps me on this.

Vulnerable libraries
Your app contains one or more libraries with known security issues. Please see this Google Help Centre article for details.

JavaScript angular.js 1.5.3 SNYK-npm:angular:20171018, SNYK-npm:angular:20180202 assets/www/lib/angular/angular.js, assets/www/lib/angular-animate/angular-animate.min.js, assets/www/lib/ionic/js/angular/angular-resource.js, assets/www/lib/angular-sanitize/angular-sanitize.js, assets/www/lib/angular-sanitize/angular-sanitize.min.js, assets/www/lib/ionic/js/angular/angular-sanitize.js, assets/www/lib/ionic/js/angular/angular-resource.min.js, assets/www/lib/angular/angular.min.js, assets/www/lib/ionic/js/angular/angular-animate.js, assets/www/lib/ionic/js/angular/angular-sanitize.min.js, assets/www/lib/ionic/js/angular/angular-animate.min.js, assets/www/lib/angular-animate/angular-animate.js, assets/www/lib/ionic/js/angular/angular.min.js, assets/www/lib/ionic/js/angular/angular.js

**Comment by rahilkalia1234** [comment]
> contains one or more libraries with known secur

Did you get your answer ?

**Comment by shankari** [comment]
Please see the history of the issue.
- Check the CVE repository for the library that is flagged
- If you don't find anything, file an SO question

The SO question for my dependencies has not been answered.
But you should *check for the library that is flagged in your case*.

**Comment by hathemi** [comment]
@venu198 i have exactly the same problem ? did you find a solution please?

**Comment by mahmoudRefaey** [comment]
> Can you help me what's the issue is this. Really thanks to one who helps me on this.
> 
> Vulnerable libraries Your app contains one or more libraries with known security issues. Please see this Google Help Centre article for details.
> 
> JavaScript angular.js 1.5.3 SNYK-npm:angular:20171018, SNYK-npm:angular:20180202 assets/www/lib/angular/angular.js, assets/www/lib/angular-animate/angular-animate.min.js, assets/www/lib/ionic/js/angular/angular-resource.js, assets/www/lib/angular-sanitize/angular-sanitize.js, assets/www/lib/angular-sanitize/angular-sanitize.min.js, assets/www/lib/ionic/js/angular/angular-sanitize.js, assets/www/lib/ionic/js/angular/angular-resource.min.js, assets/www/lib/angular/angular.min.js, assets/www/lib/ionic/js/angular/angular-animate.js, assets/www/lib/ionic/js/angular/angular-sanitize.min.js, assets/www/lib/ionic/js/angular/angular-animate.min.js, assets/www/lib/angular-animate/angular-animate.js, assets/www/lib/ionic/js/angular/angular.min.js, assets/www/lib/ionic/js/angular/angular.js

how you solve this issue
