### ISSUE TITLE
a question about inferred section

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#466]
@shankari 
in your thesis, "The correspondence between inferred and
cleaned sections is 1:1".
However in our data there are many more cleaned sections (ca. 9000) than inferred sections (ca. 4000).
Does it mean that for some reason we had problems at one time with the pipeline and that we should reset and rerun it for all data ?

Can you also confirm that the inferred section data is a clone/copy of the cleaned section data, with only 2 fields different : the id of the corresponding cleaned section, and the sensed_mode.
 there should be one inferred section for each cleaned section?

**Comment by shankari** [comment]
I just checked the code again, and the expectation is definitely 1:1 for cleaned : inferred sections.
Concretely, the flow is:
- [we get the list of sections to predict](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py#L44)
- [we get a prediction for each `self.toPredictSections`](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py#L65)
- [we save each of the predicted probabilities](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py#L79)

The only reason why this may fail is that we are not maintaining the pipeline state correctly and the query to return the sections to be inferred is returning a subset of the values. This could be because [we don't set the lastSectionDone correctly](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py#L107) when there are errors in this step.

Can you look for the sections without a match and see if there is a pattern to them - e.g. something like 

```
for cs in edb.get_analysis_timeseries_db().find({"metadata.key": "analysis/cleaned_section"}):
    match = edb.get_analysis_timeseries_db().find_one({"metadata.key": "analysis/inferred_section",
        "data.cleaned_section": cs["_id"]})
    if match is None:
        print("Found missing match for cleaned section %s %s -> %s" % (cs["_id"], cs["data"]["start_fmt_time"], cs["data"]["end_fmt_time"])
```

**Comment by PatGendre** [comment]
@shankari  thanks!
I've found 5894 cleaned sections without a match.
The section date is between June 12 and August 4. The sections are not in chronological order.

**Comment by PatGendre** [comment]
@shankari thanks a lot for the explanation! This must be it. This confirms my idea of trying to implement a public transport data dedicated overpass API (if I can find resources for that...), it would nicer not to overload the public overpass server.

I think I will simply reset the pipeline and let run the cron tonight, first for a few users so as to check the time it takes and to see if the inferred sections are back. I'll tell you !

**Comment by shankari** [comment]
> This confirms my idea of trying to implement a public transport data dedicated overpass API (if I can find resources for that...), it would nicer not to overload the public overpass server.

That would be a great supporting resource!

**Comment by PatGendre** [comment]
@shankari 
I relaunched the pipeline, and now I have a 1:1 between inferred and cleaned sections!
I ran in two waves, It took 1/2h for the first wave but 4 hours for the second, the intake console log takes 760 MB!
Surprisingly the number of cleaned sections was divided by a factor 2, and the # of inferred sections remained quite stable aournd 4000.
Thanks

**Comment by shankari** [comment]
@PatGendre 

>  I relaunched the pipeline, and now I have a 1:1 between inferred and cleaned sections!

Interesting! So it looks like probably when you were relaunching the pipeline before the overpass fix, there were duplicate cleaned sections generated? I'm guessing that this may be due to the AssertionErrors in the `CLEAN_AND_RESAMPLE` that were causing the pipeline state to not be updated although the sections were stored.

I checked in the fix to disable the asserts through a config option on Aug 5 (https://github.com/e-mission/e-mission-server/commit/a1720447cf3200fcd8c70df6670f114ebb2f68fc) 😄 

I should probably go back and fix that so that we don't save the entries until the very end so that we don't end up with such duplicate entries later.

**Comment by PatGendre** [comment]
Yes, thanks for your insight, I did not suspect it could be a problem of duplicate data (the # of trips, places and stops decreased also drastically after the pipeline was run), so this may be rather the Aug5 commit which corresponds to the date where the problems with the duplicate cleaned_sections seems to disappear.
