### ISSUE TITLE
how to get from post-trip-prompt to daily-trip-prompt?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#477]
hI @shankari 
for the needs of a pilot site, we'd like to ask for trip confirm only once a day (i.e at fixed time) instead of at the end of each trip, and ask the user about mode (not purpose) ar maybe only whether she/he rode the bicycle for the trips of the day.
What will we have to modify? Does it all happen [in the post-trip-prompt.js file](https://github.com/e-mission/e-mission-phone/blob/master/www/js/tripconfirm/post-trip-prompt.js)?

**Comment by tnariIcia** [comment]
Hi @shankari in the file [post-trip-prompt.js](https://github.com/e-mission/e-mission-phone/blob/master/www/js/tripconfirm/post-trip-prompt.js#L66) if i comment the add event listener, is it enough to disable the notification for each end of trip?

**Comment by shankari** [comment]
@PatGendre the `post-trip-prompt` is only for prompting at the end of the trip.

For prompting at the end of the day, you can use the local notification plugin directly.  Note that I use a fork with some custom changes. 
https://github.com/e-mission/e-mission-phone/blob/master/config.cordovabuild.xml#L105

@tnariIcia yup. Feel free to look at the other branches (e.g. `rk-unsw`) to see the commented out code.

**Comment by shankari** [comment]
@PatGendre note that you still need to figure out what 'end of day' means to a user - there are people who go to bed at 2am and people who go to bed at 10pm. Maybe make this be configurable as part of the onboarding?

**Comment by PatGendre** [comment]
@shankari thanks for your answers @tnariIcia , I agree that the notification time should be configurable; we were considering the morning e.g. 8am rather than the evening (the users are students who are supposed to go to the university), because it seemed less variable, but still configurability is a good idea.

**Comment by shankari** [comment]
@PatGendre @tnariIcia can you update the prompt documentation when you have finished implementing this, and close this issue?

**Comment by PatGendre** [comment]
@shankari @tnariIcia Ok, we'll update this page https://e-mission.readthedocs.io/en/latest/dev/tutorial/small_ui_changes/change_trip_end_prompt/#change-the-trip-end-prompt

**Comment by shankari** [comment]
@PatGendre is there an update to this page?

**Comment by PatGendre** [comment]
@shankari no, sorry :-( 
The question was related to the transway project in Nantes so I don't how they implemented the question feature. You can may be ask Stéphanie if she remembers this? (I don't know her user name on github).

**Comment by shankari** [comment]
@stephhuerre did you implement the question feature? If so, would be great if you could update the prompt documentation

**Comment by stephhuerre** [comment]
@shankari we did end implementing the feature. 
In fact, @tnariIcia actually implemented the feature and would be in a better position to document it.

**Comment by tnariIcia** [comment]
I will do it tomorrow.

**Comment by tnariIcia** [comment]
@stephhuerre The feature is on your repository, i sent you a documentation about it by email.

**Comment by stephhuerre** [comment]
@shankari @tnariIcia, I no longer work with Transway. I recommend you talk directly with @ericafenyo about pushing this feature.

**Comment by ericafenyo** [comment]
@shankari @stephhuerre @PatGendre 
I am in contact with @tnariIcia to push the correct code for the scheduling.

**Comment by ericafenyo** [comment]
Bonjour @shankari @stephhuerre @PatGendre
It is a while since I heard from @tnariIcia. In the meantime, I created some [github gists](https://gist.github.com/ericafenyo/d33c4a08afde2afaf0e7125fc8bd51ea) for the required files, as indicated in his docs. There were other commit messages (in our repo) not stated in the docs, so I think he will be the right person to push the code. I can send the repo if required. Thanks.

**Comment by shankari** [comment]
@ericafenyo if you could trim the code in that gist to only the new part (e.g. to https://github.com/e-mission/e-mission-docs/blob/d312e28295ce5c53e40088388c736048261fc6a7/docs/dev/tutorial/small_ui_changes/simple_client_changes.md) `setReminderNotification`) and add a link to it in the docs, that would be good enough. Only some deployers will want to have day-end notifications, others may want to have trip-end notifications, others may want to push from the server.

It is just easier for deployers to copy and paste code that they know works, rather than experiment from scratch.
