### ISSUE TITLE
explaining the process (from the phone raw logs to the server trip data)

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#48]
Hi,
we have installed the whole server + app, and it works! but we don't understand yet ow does the data go from the phone to the server and then how do the tracks become trip information and get processed to compute indicators and maps. We have clues but have not found a documentation page explaining this., an overview of the process would be useful to add in the docs, a detailed doc is not necessary though.

I list our numerous questions below, the explanations 
- first from the phone to the server : we have used the dev mode in the profile so as to force trip start and trip end, but if don't do that, how does that work for determining automatically the trip start and end? when is the data sent? we can have a look at put requests to the server in the logs so as to have some clues but it would help us a lot to know the rules that fire the data feed and where is the code are the API calls made. There is a GET for sync_server_to_phone ad a PUT for sync_phone_to_server, what does that do exactly? Is the data sent at regularly intervals or on event occurrence, probably a mix of both?
How does the usercache work?

- the second step, as we understand it, that the raw timeseries data goes thru a pipeline towards the analysis store where it is transformed into trips and sections, where it is classified by modes, but we did not find where the map matching occurs, there must be a place in the code where local OSM data is used and the GPS tracks snapped to OSM segments.
Also, for public transport, can e-mission make use of PT network information so as to match sections and lines/routes? There is somewhere a mention of Conveyal's modeify lib but is it actually used, and what for?

Thank you

**Comment by shankari** [comment]
> but if don't do that, how does that work for determining automatically the trip start and end? when is the data sent?

trip start and end are determined automatically in native code, in the https://github.com/e-mission/e-mission-data-collection plugin, to be precise

> Is the data sent at regularly intervals or on event occurrence, probably a mix of both?

you can see this from the em-arch paper
- on android, the data is sent periodically. the default sync interval is an hour, but can vary depending on doze mode. the value can be configured using javascript.
- on iOS, since background operation is restricted, the data is sent at the end of every trip, and if you have the silent push notification cronjob enabled, when the silent push notification is received.
The sync is invoked in the https://github.com/e-mission/cordova-server-sync plugin

> How does the usercache work?
Again, there is a native plugin https://github.com/e-mission/cordova-usercache. This basically caches locally generated data into a local sqlite database, and then push/pulls to the server when the sync (see above) is triggered.

> but we did not find where the map matching occurs, there must be a place in the code where local OSM data is used and the GPS tracks snapped to OSM segments.
we don't actually do full map matching to OSM segments. We primarily look at the start and end points of _sections_ not _trips_ and compare them to public transport stops. This code is currently in a branch (https://github.com/e-mission/e-mission-server/pull/578). We use the overpass server to query specific POI near the start and end points.

**Comment by shankari** [comment]
If I have answered all your questions, please close this issue. Otherwise, ask for more clarifications :)

**Comment by shankari** [comment]
oh wait one more:

> Also, for public transport, can e-mission make use of PT network information so as to match sections and lines/routes? There is somewhere a mention of Conveyal's modeify lib but is it actually used, and what for?

Yes, it uses the PT network information in OSM, in particular the route information associated with stops near start/end points to determine the mode of transportation. It actually uses the route information for the matching (e.g. if my start is near route x and my end is near route x, then I probably took route x), so it should be possible to return the route x in almost all cases where it is available.

**Comment by PatGendre** [comment]
thanks of a lot for the clear and complete answers!
I must admit we didn't look at the native code for data-collection and usercache, thanks for pointing out the 2 codes to us.

Thanks for the explanation about OSM data usage, this means that for the area we intend to work on, we'll have to check if PT stops are available and correct, or else contribute to the OSM database with PT data.
Do you sometimes experience timeouts when querying the overpass API?

Wrt modeify, I asked because it is mentioned in the server doc here
https://github.com/e-mission/e-mission-server/blob/master/modeify.md
but didn't find modeify in the code, sorry.

I close the issue.

**Comment by shankari** [comment]
Briefly reopening to address a couple of more points.

**Comment by shankari** [comment]
> Thanks for the explanation about OSM data usage, this means that for the area we intend to work on, we'll have to check if PT stops are available and correct, or else contribute to the OSM database with PT data.

Yes, the mode inference is only as good as the underlying OSM data. In particular, the mode inference, including for the actual route, is vastly improved if the underlying data is in the new format (e.g. with route relations) rather than with the old format (e.g. with `highway/bus_stop`). As I said, we don't do map matching right now, but if we did, then having the route relations would be absolutely critical.

>  Do you sometimes experience timeouts when querying the overpass API?

I don't think so. I'm using the "Main Overpass API instance" from https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances, which is supposed to handle `10,000` queries per day. If your query volume is anticipated to be high, maybe drop a message to the maintainer and check whether they are seeing issues.

If you want even better reliability, you can always run your own server, since overpass is open source as well.

> Wrt modeify, I asked because it is mentioned in the server doc here
https://github.com/e-mission/e-mission-server/blob/master/modeify.md
but didn't find modeify in the code, sorry.

Yeah that is a failed integration attempt, currently abandoned. Will remove and then close this issue.

**Comment by PatGendre** [comment]
Thanks for these new pieces of info !
