### ISSUE TITLE
trip planner, zephyr, user management, trip validation

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#49]
hi
we have just installed e-mission on our own server. I file here a few questions about , sorry if some of them are already answered in the docs but we did not find where.

**trip planner**:
- there is a trip planner screen on the mobile app but it seems to be an external app specific to the Bay Area? (em-planner)
- opentripplanner is part of the external code but is not deployed when we install the server, maybe this is what powers the trip planner?

**zephyr**
- what is Zephyr? Is that a part of the e-mission code, or maybe a specific use case of the framework?

**user management**
- how do we create a user from the server side? Is there some kind of back-office ?

**trip validation**
- is there a way for the user to validate / improve the trip diary data? There is a fix map button but it is said it will work in March...

thank you

**Comment by shankari** [comment]
>     there is a trip planner screen on the mobile app but it seems to be an external app specific to the Bay Area? (em-planner)
>     opentripplanner is part of the external code but is not deployed when we install the server, maybe this is what powers the trip planner?

Yes. We had an installation of OTP linked as em-planner to experiment with routing. But that integration was not popular, and I had to turn off some servers because of cost, so I turned it off. I have another student who built a docker container to run OTP; if you are interested, I can ask him to submit a PR with it or upload it to dockerhub.

**Comment by shankari** [comment]
> what is Zephyr? Is that a part of the e-mission code, or maybe a specific use case of the framework?

Zephyr is a way to use battery data to evaluate the power drain of applications in a cross-platform fashion. (http://www2.eecs.berkeley.edu/Pubs/TechRpts/2018/EECS-2018-168.html) We tried submitting it a couple of times but were not successful because people refused to believe that there is a problem. I will re-use the zephyr framework for benchmarking the e-mission data collection.

> how do we create a user from the server side? Is there some kind of back-office ?

It depends on what authentication mechanism you want to use. If you want to use google auth, no. if you want to use OpenID connect, you would use the instructions for the keystone server, for example.

> is there a way for the user to validate / improve the trip diary data? There is a fix map button but it is said it will work in March...

Yup, but not on the main branch. You can try out some of the other UI clients or skins to see an example. If you want this, you would need to merge the relevant code from their branch (sorry, but this is not as nicely plugin-ified as I would like). Instructions for experimenting with different skins are in the workshop logistics.

The UNSW team is also improving the mode/purpose popup code even further.

> There is a fix map button but it is said it will work in March...

The button that was supposed to work in March was intended to run the pipeline on the fly instead of in the hourly cronjob. It won't really fix the map. There's a PR in which @sunil07t tried to fully fix the trip (not just specify the primary mode), but I don't think it was tested extensively. Then @megumi had her team try to fix it (https://github.com/e-mission/e-mission-phone/pull/469) but apparently they were unable to. I am not sure what is broken; if you want to try testing it and report issues, we may be able to fix it. I am not sure how extensively people want to edit their trips, though.

**Comment by shankari** [comment]
Again, please ask followup questions here or close the bug if they are all answered

**Comment by PatGendre** [comment]
Thank you again for the clear answers!
I am far from a specialist on the issue, but zephyr seems very interesting to me. We will definitely interested when you publish benchmarks using zephyr.

For the proof of concept this semester, I don't think we'll need OTP.
We don't think that the user will want to edit maps, too. But completing or correcting the mode detection, maybe, also this is not the first feature we expect to work on.

It will be a pleasure to talk to you next Monday.
I close the issue

**Comment by shankari** [comment]
>  We don't think that the user will want to edit maps, too. But completing or correcting the mode detection, maybe, also this is not the first feature we expect to work on.

The Sydney group (@atton16, @asiripanich) are actively working on improving the existing completing/correcting mode detection feature. So you might want to wait until they are done and then build on their work.
