### ISSUE TITLE
limesurvey : No token in survey id

### ISSUE THREAD

**Issue by dev-rod** [e-mission/e-mission-docs#491]
Hi Shankari,
we have installed and configured limesurvey module, emission-server starts and run correctly,
but when we try to get limesurvey questions from app mobile, we have in emissionpy.err.log for example:
No ef60b6ce533a498289917de0c1574162 in survey 841534
No ef60b6ce533a498289917de0c1574162 in survey 114168
No ef60b6ce533a498289917de0c1574162 in survey 158938
No ef60b6ce533a498289917de0c1574162 in survey 434636
No ef60b6ce533a498289917de0c1574162 in survey 458448
No ef60b6ce533a498289917de0c1574162 in survey 657556
i suppose ef60b6ce533a498289917de0c1574162  is a token identifier
have you an idea on what we missed ? Thanks a lot 
Best regards

**Comment by shankari** [comment]
@dev-rod the limesurvey module was developed by FabMob and has not been contributed to the main e-mission repo. Although I think you can argue that it should be 😄 Since I didn't review the code as part of a PR, I am not sure how it works.

@PatGendre can you answer this question about lime survey? You could also consider submitting it as a PR to master so that I can review the change...

**Comment by PatGendre** [comment]
Hi @dev-rod @shankari as you know this module has been developed by Loic @DO3B  as a student job last summer. It maps the limesurvey id with the e-mission user id in a mongodb collection named Stage_push_token_mapping. 
@dev-rod you should start by checking that your limesurvey instance works fine, I guess you have installed and configured your own instance? The documentation is quite detailed https://fabmob.readthedocs.io/en/latest/manage/adding_limesurvey_support/

Then the limesurvey configuration in e-mission is not very easy but if done carefully it should work.
As far as I am concerned we did not encounter any error in the limesurvey app code, that's why I recommend first to check that the limesurvey server and the e-mission server are working before checking the app side.

@shankari : thanks for proposing to review the limesurvey code, there is code both on the e-mission-server (net/ext_service + conf) and an e-mission-phone (screen template  + js) sides, so I will check with Yann and Tristant what we need exactly to submit in the PR.

**Comment by shankari** [comment]
@dev-rod have you been able to resolve this? If so, can you please close the issue?

**Comment by dev-rod** [comment]
yes thanks, resolved with @PatGendre
