### ISSUE TITLE
Invalid time on trip

### ISSUE THREAD

**Issue by stephhuerre** [e-mission/e-mission-docs#498]
Hi @shankari,

Our trips from January 30th and 31st had an undefined date `Invalid dateHundefined`.

After some investigation we found that the month value of `tripgj.data.properties.start_local_dt` received from the database was equal to 1 (which corresponds to February). Since there are only 29 days in February, the 30th and 31th return an erreur.

How should this appropriately be fixed on the server side ? 

In the mean time, we fixed it by replacing `tripgj.data.properties.start_local_dt` with `tripgj.data.properties.start_fmt_time` in list.js, line 210 and 211. 

Thanks!

**Comment by shankari** [comment]
@stephhuerre there is an open PR to fix this (https://github.com/e-mission/e-mission-phone/pull/615) in which I suggested the principled fix (we should keep the server untouched and fix the client, so that both draft trips and processed trips can be fixed). Unfotunately, @atton16 has not yet updated the PR. If you want to implement a Right Fix and submit it to master, that would be great!

**Comment by shankari** [comment]
Right Fix checked in 8537d9d4d05d7361fe8cf9ea6871411abd962f43
Thanks to Transway for the contribution.
