### ISSUE TITLE
Feature request: a invitation code based approach to join a deployment

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#540]
Can we have an invitation code based approach to join a study? I've got some complaints from our testers and participants that the on-boarding process is quite unusual.. download the app and go back to click on the join study link is not what most people are familiar with when they download an app on their phone. So if we can have a text box that allows users to input an invitation code to a specific study that would be great.

**Comment by shankari** [comment]
@asiripanich couple of clarifications:

1. we cannot change the on-boarding process without upgrading the native app. You can customize anything that happens after the user scans the QR code. Anything before that is in the published app and will require a new app submission, and go through app store review.
1. are your testers and participants from the travel survey world? Because in the live preview world (e.g. Expo https://expo.io/tools), scanning a QR code is the standard way to switch to a project. Ionic had a similar product, but Apple removed the app from the stores, which is also why I am reluctant to update emTripLog until your study is done
1. Using a QR code allows you to pass in more complex parameter, similar to the request for #508. Note that unlike a traditional travel survey app which essentially has the same UI, we allow the entire UI to be configurable.

Having said all that, I think it would be worth considering how to include it in the next native release of emTripLog. This also seems to be similar to https://github.com/e-mission/e-mission-docs/issues/452 so would be worthwhile to plan out a common strategy for both....

**Comment by shankari** [comment]
Note also that traditional travel survey apps are essentially systems. They have one UI, one server, and one "operator" who manages the survey creation and the server. The group running the survey can log into the shared server using some kind of dashboard. However, in the case of emTripLog, each study runs their own server. So there is no shared emTripLog server whose URL we can hardcode into the app to retrieve survey parameters.

**Comment by shankari** [comment]
> download the app and go back to click on the join study link is not what most people are familiar with when they download an app on their phone.

I think I'm still struggling with whether this request is just due to resistance to new concepts or whether it is objectively better. Because one of the standard rules of UI design is that you should avoid having the users type on the phone.
e.g. https://xd.adobe.com/ideas/principles/app-design/10-dos-donts-mobile-app-design/

> **8. Minimize the need for typing**
>  Typing on a mobile device is a slow and error-prone process. It’s, therefore, always best to try to minimize the amount of typing required on a small device.

there is even a formal academic study comparing QR codes with OTPs in terms of design (https://www.nngroup.com/articles/mobile-login-china/)

> OTPs have a higher interaction cost than QR codes— they require users to type a code (or copy and paste it from the text-message app into the password field).

https://www.sitepoint.com/7-best-practices-designing-mobile-user-experience/

> Small touch screens and yet smaller virtual keyboards with keys that are barely 5mm x 5mm in size do not make for a happy typing experience. As far as possible, pre-fill fields with defaults. Use auto-fill for commonly used fields.

-------

The invitation code is not embedded into emTripLog. So with either the QR code approach or the invitation code approach, the user would has to install the app and then go back to the enrollment page to get the invitation code.

Once they go back to the enrollment page:
1. with the current approach, they need to click on a button or scan a QR code,
1. with the proposed approach, they need to type out a code on the phone

According to all the rules of UX design above, option (2) is worse. Obviously, if you don't have the sophistication to support deep-linking, you have to use auth codes. But we do :smile:

In general, I don't like to argue about UX design because people have different opinions and is hard to come up with an objective test. Which is why I made the UX configurable. But unfortunately, this part of the UI is for the common, non customizable part, which means we do have to argue about it :smile:

@PatGendre if you want to add your thoughts on customization (related to #452) that would be helpful.

**Comment by PatGendre** [comment]
@shankari @asiripanich Hi, I am not a designer but my opinion is that QR code scanning would be Ok for the vast majority of user. I think it is not only a "pure UI" issue, it is UX in the larger sense : the installation instructions / onboarding process have to be very clear, and there should be also a minimal number of screens for the end-users to go through.   

Although we did not use the in QR code scanning / UI channels in our tests in France, I still find it very relevant for adapting to various sites without changing the app. 

> However, Apple removed the apps from the  stores

If there is a risk that this kind of UI channel apps is not allowed in the Apple Store anymore this is a serious issue?

**Comment by shankari** [comment]
> If there is a risk that this kind of UI channel apps is not allowed in the Apple Store anymore this is a serious issue?

There are other apps that Apple does allow - e.g. Expo https://expo.io/tools. And updating UI through channels without allowing some form of selection is still supported, including with Ionic Deploy (which is what I use) and CodePush (https://docs.microsoft.com/en-us/appcenter/distribution/codepush/) which is from Microsoft.

So I think that it comes down to how you brand the app. If you brand it as a "developer testing app" then it will get rejected. That's why I have been careful to brand it as a way to customize studies "intended to be used by other researchers to conduct studies on human travel data.", which is what it is.

Haven't been rejected yet, but I always feel nervous when I submit to the store. If it gets rejected, then every researcher will have to build and submit a custom app. Hopefully, we will make the building process smoother before then, maybe through integration with Fastlane.

**Comment by shankari** [comment]
@asiripanich I thought about this a bit more overnight, and this may actually be a nice section in the paper.

The goal of (methodological) research is to propose innovative techniques based on the literature, implement them and report the results.

Here:
- we are proposing an innovation (scan/click instead of type) based on the UI literature (see examples above).
- We have implemented it.
- Since the result is not what we would expect, people will want to know why.

Is the result purely due to familiarity and will go away as people adapt to the new method? Or is this really a case where the conventional UX wisdom is wrong? In either case, this will be a good section in the final paper :)

**Comment by asiripanich** [comment]
@shankari That sounds interesting, but I have to admit that I don't know anything on this particular topic so I'm relying on your expert opinion. I can include some questions that ask participants directly about this topic. Do you have any recommendation to how we should phrase such questions? and what type of response do we want to those questions?

**Comment by asiripanich** [comment]
> @shankari @asiripanich Hi, I am not a designer but my opinion is that QR code scanning would be Ok for the vast majority of user. I think it is not only a "pure UI" issue, it is UX in the larger sense : the installation instructions / onboarding process have to be very clear, and there should be also a minimal number of screens for the end-users to go through.
> 
> Although we did not use the in QR code scanning / UI channels in our tests in France, I still find it very relevant for adapting to various sites without changing the app.
> 
> > However, Apple removed the apps from the  stores
> 
> If there is a risk that this kind of UI channel apps is not allowed in the Apple Store anymore this is a serious issue?

Totally agree with you that we need less screens and I think it is something that should be on our agenda. How the OSes and OEMs are treating location tracking apps are very worrisome for deployers.

**Comment by shankari** [comment]
> so I'm relying on your expert opinion

I am not a UX expert, but the "typing on mobile screens is hard" concept is widely known in the tech community.

I looked at the travel survey recruitment page again, and I wonder if one cause of confusion might be that there are multiple QR codes on the page. This actually happened to somebody else whom I sent the tripaware live demo to. They scanned the emTripLog installation QR code a second time.

I am not a survey expert, but I think it would be useful to, more broadly, figure out how people navigate the survey instruction page. For e.g.:
- how are people accessing the instructions (on their phone or on a desktop)?
   - if on a phone, do they use the store button, or search for the app in the store?
   - if on a desktop, do they scan the QR code or search for the app in the store?
- after installing the app, do they use the link or the QR code to customize?
- when they see the survey instruction page, what is their primary impression?
   - what do they see as the focal point of the page?
   - which elements are clear?
   - which are confusing?

And as part of this broad discussion, maybe an open ended question that allows people to reflect on the differences between this new link/QR code method and the traditional invitation code approach.

You could say that the QR code was an attempt to conform to mobile UX best practices, and we are trying to understand why it was confusing. Was it just actual approach, or the feeling that the survey instruction page was then too busy and there were too many instructions?

**Comment by shankari** [comment]
Closing this since the QR code approach seems to work fine for now. @asiripanich please reopen if the findings from the survey indicate otherwise.
