### ISSUE TITLE
Trips stay in draft mode

### ISSUE THREAD

**Issue by EstherEu** [e-mission/e-mission-docs#558]
So far we had a couple of phones where the trips suddenly start staying in draft mode. 
The only way to solve this was to reinstall the app.

I first checked the pipeline logs and tried a user-specific pipeline run but nothing seems to be wrong there (as far as I can tell).

Then I tried a force sync on the client (and I could see on the server console the "POST userchache/get ...")
Everything seems to be working, except the trips stay in draft mode. 

Finally I checked the user cache on the server and the trips don't appear to be there. For the affected uuids I only see "background/location" entries up to a certain date (the date where the trips start staying in draft mode). 
After that date the only user cache entries for the affected uuids are the ones with the keys "stats/pipeline_time" or "stats/server_api_time". 
So my guess is that the phone suddenly stopped sending the data to the server for some reason.

Do you have any advice on how to fix this or how to find out what is causing this?

**Comment by shankari** [comment]
@EstherEu If you search for "draft mode" in the existing issues
https://github.com/e-mission/e-mission-docs/issues?q=is%3Aissue+draft+mode+is%3Aclosed

you might see that this (https://github.com/e-mission/e-mission-docs/issues/283) is similar. Have you checked to see if it is the same problem?

Note also from (https://github.com/e-mission/e-mission-docs/issues/443) that this is fixed in the more recent versions of the app. If that is indeed the problem, I would recommend upgrading instead of bumping up the ngnix RP payload.
