### ISSUE TITLE
setting up an e-mission instance

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#591]
Hi, we will start again working on e-mission with Yann and Fouad this week , the goal is to deploy a new instance for a project in la Rochelle (a small city on the French atlantic coast), for a 2-year pilot test focused on carbon emissions. The app will be made public after a few months in 2021, with FabMob.

For the server, which branch is recommended ? Can we still used the GIS branch or is it best to use Master branch if GIS is merged into it shortly? In the docs, your recommend to deploy on docker, what are the main reasons for that?

For the app, I suppose we shall use Master, but for our information, what are the features added in the ceo_ebike, and in the loc history projects?
Is there any change to the translation plugin, what other major changes since last year do we need to take into account?
On the play store, the e-mission is not updated, but the emtriplog app is : is it based on the Master branch?

thanks

**Comment by shankari** [comment]
Hi @PatGendre 

responses inline:
- for the server, you can use the GIS branch for now. I will merge master into it only towards the end of December
- I recommend docker because I have created an example with a multi-tier architecture that has everything set up with a single command. Of course, you can also use a manual install.
- for the app, we should distinguish between the plugins and the UI
  - both ceo_ebike and loc history use the most recent version of the plugins with the default settings
  - ceo_ebike is based on the tripaware project and uses the polar bears for display
  - loc history basically uses master with some minor changes (e.g. a survey button in the profile)
- I made sure to put the generic UI fixes into master
- one change to ceo_ebike is that we ask three questions: mode, replaced mode and purpose. You may find the replaced mode important for carbon emissions as well. I have refactored the code to add a new button so it should be easy for you to add it
- I added the intro pages to the translation as well so you could have both french and spanish at the same time for example. 
- emTripLog basically has all the plugins only; it is the most recent version of them. In my last email, I sent a link you can use to test it using loc history.
- the major changes relate to more principled foreground support and better error reporting in general to notify people when they don't have the correct settings

**Comment by shankari** [comment]
oh and the dashboard is new and cool - it now works with the master branch. I will be extending it to work with customizable user inputs in the next month.

**Comment by PatGendre** [comment]
Hi @shankari , thanks for all the answers:-)
So we'll stick on the GIS branch for the server and Master branch for the app.
And probably on the manuel install, although I'm pretty much convinced in the long run it is really worth investing into docker.
We'll see if we need to add new buttons later on...
And I'll try to install the R dashboard when I find time, it looks definitely great.

> In my last email, I sent a link you can use to test it using loc history.

I've found this link that you sent https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=NRELlh
But I returns an "invalid study reference ... Gplay edu.berkeley.eecs.embase" when I scan it from emtriplog

**Comment by PatGendre** [comment]
Hi @shankari even if Yann won't use the docker install for now as we will be on the GIS branch,   
 I've tried myself but after `sudo docker-compose up`, I am getting this :       
`Step 2/5 : COPY conf /conf
ERROR: Service 'analysis-server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder650863291/conf: no such file or directory
`
I think this is because there is no "conf" file in https://github.com/e-mission/e-mission-docker/tree/master/examples/em-server-multi-tier-cronjob , am I correct ?

**Comment by shankari** [comment]
> I've found this link that you sent https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=NRELlh
> But I returns an "invalid study reference ... Gplay edu.berkeley.eecs.embase" when I scan it from emtriplog

You need to scan the second QR code.
The first is a QR code for the app.
The second is for the study.

**Comment by shankari** [comment]
@PatGendre you can use the docker install with any branch. See the `SERVER_BRANCH` environment variable in docker compose

**Comment by PatGendre** [comment]
> You need to scan the second QR code. The first is a QR code for the app.

Sorry, I have to learn reading in the first place! 
The app works fine, by the way the consent / intro explanations are great, this can inspire us for our terms of use in la Rochelle:-) Enketo is great, too!
I wonder why there is a signup for the goals menu?

**Comment by PatGendre** [comment]
> you can use the docker install with any branch

Thanks, I tested, with no other additional conf, and it worked :-) The web server is up and running, a first step!
I will try the docker emdash next time;-)

**Comment by shankari** [comment]
>  I wonder why there is a signup for the goals menu?

Because the team has not yet removed it. I've been pushing for the group at NREL that is actually conducting the study to customize the app since it is not a sustainable option for me to customize for each use case. I might remove from master when I get a chance and then it will go away automatically.

**Comment by shankari** [comment]
"The app works fine," 👍 

If you have it installed for 3-4 days, then the loc history project can use your data for the modelling 👍

**Comment by PatGendre** [comment]
I've also tested quickly the emdash docker image, it seems to work fine, too, but this needs to be configured so that the R dashboard is connected with the local e-mission server and fed with test data, so this is not so easy to go further because all is containerized, I'll check this when I find time...

**Comment by shankari** [comment]
@PatGendre the assumption is that you can use ssh tunneling to access the cloud database from your laptop, but do it securely. No need to copy anything in that case.
https://github.com/asiripanich/emdash#run-locally

You can contact @asiripanich for more help with emdash.

**Comment by PatGendre** [comment]
@shankari thank you! I'll test ssh tunneling when our server is set up. And if needed I'll contact @asiripanich ;-)
