### ISSUE TITLE
Permissions for the e-mission-phone app on Android 11 does not incite to allow background location

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#608]
Hi @shankari 
This is not a bug but for FYI
I forward an issue made by Maël of Fabrique des Mobilités when he installed our tracemob e-mission app : When he first went through the setup screen, he didn't see the green link to enable permanent access to the location API (via the app parameters).
This way of presenting the permissions seems new on Android11 (my permissions screen show equally the authorization for background location than for foreground)
![permission-screen](https://user-images.githubusercontent.com/5039447/106174899-c6e74a00-6195-11eb-9915-e4d2fb219bdf.jpg)

"This is Android 11 on a Samsung S10e. As you can see, a user that is impatient to test the app will click on the most obvious link "only when the application is open", which makes the whole app unusable without any message. I had to reset the app data, remove, reinstall, and set the permssion correctly to make it work again.

This may have been explained in the text, but I didn't care to read it (too much) and I believe it might be the case for most people."

**Comment by shankari** [comment]
@PatGendre Let me test on android 11, at least on the emulator. I believe that if we don't have the "always" permission on android, the app will generate a prompt periodically (~ 1 hour) asking to turn on the always permission. Can Maël reinstall with "only while using the app", see if he gets the notification and see if it works to turn on the "always" permission?

**Comment by PatGendre** [comment]
@shankari thanks, I  asked Mael to test. The app was not working well when with the "only while using the app" permission, and worked with the background location on, but I cannot tell you the exact behavior wrt notifications.

**Comment by laem** [comment]
Yes, I first tested with the "only while in use" option, and it resulted in a blank screen, the app was not usable.

**Comment by shankari** [comment]
@laem I plan to fix this soon. I will test on the emulator, of course, but would you be able to test on a real phone?

**Comment by shankari** [comment]
So in android 11, it is apparently possible to go to the location permissions screen directly, but if the user does not accept it, then you can never use it again.
https://stackoverflow.com/a/64282458/4040267

I will explore that in greater detail once I switch to API 30. For now, if the android version is > 29, I will just bring up the app permission screen instead of prompting the user. That seems like a fairly simple change to make and will not require me to migrate to API 30 and deal with any regressions.

https://stackoverflow.com/a/32983128/4040267

**Comment by shankari** [comment]
Alas, this is not quite as simple. Simply launching the app settings does not fix the issue of having to know when the settings have been changed, and kicking the FSM to detect that.

So the behavior was:
- launch the settings, user selects "always", come back to app, still in start state
- launch the settings, user selects "while using", come back to app, still in start state, no error notifications

Fixed this by using `startActivityForResult`. This took a while to get working because I didn't call `cordova.setActivityResultCallback` first. Doh!

After setting the callback, we are now notified when the user returns from the settings screen. We then cancel any notifications that are no longer relevant, and re-run the checks.

New behavior:
- launch the settings, user doesn't change anything, come back to app, error about location permission, click
- launch the settings again, user switches to "when in use", come back to app, error about background permission, click
- launch the settings again, user switches to "always", come back to app, no additional errors, now in waiting_for_trip_start
