### ISSUE TITLE
describe the car emission parameters in the the user profile?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#629]
Looking at the server code https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/core/wrapper/user.py    
it seems that the e-mission was initially designed so that the user could describe his/her car(s) in the app, so as to better estimate the carbon emissions. Is there still a project using this feature, is it available on a particular branch?   
Thanks

**Comment by shankari** [comment]
@PatGendre yes, describing the car(s) in the onboarding flow was one of the initial features.

We ran into problems fairly quickly, though, because most American households have multiple cars (e.g. a commute car for each spouse and a pickup truck) and, as you might imagine, we could not automatically determine the car type from the sensed data.

However, now that we have user labels for the data, we can include the various car models into the mode choice drop down.

And NREL also really cares about this feature, as you might expect given our focus on EVs. So I think we will reintroduce it as part of the big label redesign over the summer.
