### ISSUE TITLE
a problem with timezone for the pipeline?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#653]
@shankari Hi, we noticed since a few weeks that although the intake multiprocess pipeline is run each night at 1am, it processes data only until 11pm, so the trips after 11pm are processes only the night after. (I think the issue exists since we installed the server for the la Rochelle project)
In the pipeline state collection in mongodb, the last_ts_run contains timestamp corresponding to 11pm so this is coherent.
I don't understand where in the conde or conf the problem comes from, but this 2 hour lag is also the difference between France/Paris time and UTC so I suspect the time query is done in UTC whereas the server time is in Paris time?
Thanks in advance.

**Comment by shankari** [comment]
@PatGendre the end of the time query is "now"
https://github.com/e-mission/e-mission-server/blob/72d1ee69728cc310c54571ab3b819cf41fbf3d77/emission/storage/pipeline_queries.py#L285

I agree that this seems to be due to the differences in timezone between France and UTC. Can you check the timezone on the server? You can also look at the pipeline logs - e.g something like and see what the timestamps are

```
2021-07-04 21:15:08,994:DEBUG:139767130564416:curr_query = {'invalid': {'$exists': False}, 'user_id': UUID('1fdbfb17-5168-445a-8c2b-14efd528ccdd'), '$or': [{'metadata.key': 'background/filtered_location'}], 'metadata.write_ts': {'$lte': 1625433303.9928074, '$gte': 1624743156.967006}}, sort_key = metadata.write_ts
```

**Comment by PatGendre** [comment]
@shankari thanks, the timezone on the server is Paris time, not UTC (i.e. `date` returns the current time in France)
And in the logs too, if I do `tail -f webserver-console.log` the time is Paris time, not UTC.

**Comment by shankari** [comment]
Ok, you are running the server at 1am Paris time, which is 11am UTC. So are you saying that trips after 11pm **Paris time** don't get processed? That seems odd. How are you checking this and are you sure that your checking code is not running in UTC?

Also, can you look at the timestamps on the query for the `TRIP_SEGMENTATION` step (as above)? They will be in `/var/tmp/intake_*.log` unless you have reconfigured the log locations.

**Comment by PatGendre** [comment]
An end-user can see it because if they have a trip after 23, on the next day it appears as draft (it has not been processed by the pipeline, and gets processed the day after) ; this has been signalled a few times.    
Also, on the pipeline log, I can see that the `last_ts_run` field of the pipeline state collection contains timestamp corresponding to 11pm, not 1am.

Here is a sample of the `TRIP_SEGMENTATION` log :    
```
2021-07-09 01:00:26,156:INFO:140032669132608:For stage PipelineStages.TRIP_SEGMENTATION, start_ts is None
2021-07-09 01:00:26,179:INFO:140032669132608:For stage PipelineStages.TRIP_SEGMENTATION, last_ts_processed is unchanged
2021-07-09 01:00:26,182:DEBUG:140032669132608:Inserting entry Entry({'_id': ObjectId('60e7838a4792bdbd1d245415'), 'user_id': UUID('632
2b98e-4377-45c6-a3d4-c63ffe313667'), 'metadata': Metadata({'key': 'stats/pipeline_time', 'platform': 'server', 'write_ts': 1625785226.
181879, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2021, 'month': 7, 'day': 8, 'hour': 16, 'minute': 0, 
'second': 26, 'weekday': 3, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2021-07-08T16:00:26.181879-07:00'}), 'data': {'nam
e': 'TRIP_SEGMENTATION', 'ts': 1625785226.1818385, 'reading': 0.02614898793399334}}) into timeseries
```

**Comment by shankari** [comment]
@PatGendre can you get the `curr_query = ` line above?

**Comment by PatGendre** [comment]
`2021-07-09 01:00:26,104:DEBUG:140032669132608:curr_query = {'invalid': {'$exists': False}, 'user_id': UUID('6322b98e-4377-45c6-a3d4-c63ffe313667'), '$or': [{'metadata.key': 'manual/mode_confirm'}, {'metadata.key': 'manual/purpose_confirm'}], 'metadata.write_ts': {'$lte': 1625785221.0973938}}, sort_key = metadata.write_ts
`

**Comment by shankari** [comment]
@PatGendre that is the query from the `USER_INPUT_MATCH_INCOMING` - you can see that it is looking for `'metadata.key': 'manual/purpose_confirm'`. If you want to understand the issue with trips being processed, you should find the similar query in the `TRIP_SEGMENTATION` stage.

However, this is also useful because we query for all entries less than `1625785221.0973938`. 
`1625785221.0973938` = `2021-07-08T23:00:21.097394+00:00` = approx 1am Paris time

So it is definitely handling all entries before 1am Paris time for the `USER_INPUT_MATCH_INCOMING`.
You might want to send me the detailed intake pipeline logs for the day and user who had a trip after 23 and it was draft.
E.g. if user2 had a trip at 2021-07-03T23:XX:XX, you want to send me the intake logs for that user when the pipeline ran at 1am on 4 July.

Also, I am not sure why you run the pipeline once a day. It doesn't really save you much in resources (I think) since although it runs less frequently, it has to process more information at the time. Why not run it every hour, where it can process smaller chunks of day throughout the day? This should use less resources for any one run.

**Comment by PatGendre** [comment]
@shankari  sorry, here is better line for your request out of the log    
`2021-07-08 01:00:20,179:DEBUG:140333070370624:Inserting entry Entry({'_id': ObjectId('60e63204efdb357ad4ed9062'), 'user_id': UUID('aa4c2dc5-4ecf-4eaa-96df-f4b84137200d'), 'metadata': Metadata({'key': 'stats/pipeline_time', 'platform': 'server', 'write_ts': 1625698820.1795924, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2021, 'month': 7, 'day': 7, 'hour': 16, 'minute': 0, 'second': 20, 'weekday': 2, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2021-07-07T16:00:20.179592-07:00'}), 'data': {'name': 'TRIP_SEGMENTATION', 'ts': 1625698820.1795504, 'reading': 0.02680111536756158}}) into timeseries`

You are also right that we could run the pipeline more frequently. The idea was that once a day was simple and acceptable, but is maybe not optimal.

I send you the logs where I have grepped for the userid, thanks in advance if you can have a look.   
The user is on vacation next week but I will try to ask him if the draft trip has been processed 24h after ;-)

**Comment by shankari** [comment]
@PatGendre that is not exactly the query - it is the entry for the run. But note that the entry was written at 
1625698820.1795924 = 2021-07-07T23:00:20.179592+00:00

I think this may just be an artifact of the delay in sending data to the server, combined with running the pipeline once a day.
Note that the data is cached on the phone, and only pushed to the server periodically. On android, this happens ~ once an hour, but could be a bit longer if the phone is in doze mode.

So if the trip started after 23:00, ended after 00:00 and was pushed after 01:00, it will only be processed the next time the pipeline runs.

**Comment by PatGendre** [comment]
@shankari Ok, so we should test further.   
It may well be that some trips say at 10pm will not be processed either, if the app data is not pushed for a while to the server. If I don't forget to do it, I could for instance do a trip even at 9pm and shut off my phone right after that, so that the data did not have the time to be pushed, and then see on the next morning that it appears as draft...

Thanks for your insights

**Comment by shankari** [comment]
>  I could for instance do a trip even at 9pm and shut off my phone right after that, so that the data did not have the time to be pushed, and then see on the next morning that it appears as draft...

Correct. And it will stay as draft until the next morning.

This can be sort of fixed by running the pipeline more frequently. In that case, the trip will still appear as draft on the next morning, but will change to cleaned within an hour or so. You don't have to wait for the *next* morning to fix it.

**Comment by shankari** [comment]
Closing this since it doesn't appear to be a problem with the timezone, but rather, with the invocation interval of the pipeline. Please reopen if that is not the case.
