### ISSUE TITLE
Can the initial download UI prompt be less scary?

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#667]
Can this prompt message be changed to omit the scary bits inside { }?

![download-ui-update](https://user-images.githubusercontent.com/17020181/129932073-ef8ebbcf-320d-4700-8fa2-11d6b4e943c1.png)

**Comment by shankari** [comment]
I'm a little confused about this. We have the same code on master and on CanBikeCO.

master: https://github.com/e-mission/e-mission-phone/blob/master/www/js/splash/updatecheck.js#L151
CanBikeCO: https://github.com/e-mission/e-mission-phone/blob/ceo_ebike_project/www/js/splash/updatecheck.js#L156

But on CanBikeCO, I see the following message

<img src="https://user-images.githubusercontent.com/2423263/129939505-8fca9f41-6776-4156-9fbd-2a0d9374434e.png" width="240px"/>

**Comment by shankari** [comment]
ok.. checking the logs for the display above, I get

```
DEBUG:Ionic Deploy: Update available: {"build":7404635,"snapshot":"8797b59a-10ec-4ba7-977e-ca40e0de2fdb","compatible":true,"available":true,"partial":false,"url":"https://api.ionicjs.com/apps/9f7dc506/snapshots/8797b59a-10ec-4ba7-977e-ca40e0de2fdb/manifest","incompatibleUpdateAvailable":false}
```

so why isn't the full updatecheck serialized?

**Comment by asiripanich** [comment]
I also dont see that after subsequent updates, only the first one during the on-boarding process.

**Comment by shankari** [comment]
yeah I figured it out yesterday, but didn't update because I was busy deploying the final fixes to the auto-labeling. 
Although both master and CEO ebike project have the same code, the main emTripLog is not built from either for those. It is built from https://github.com/e-mission/e-mission-base which is a stripped down version of the phone which has sensing and not UI.

And since it doesn't have the UI, I did not merge over the i18n changes. So the implementation there is:
https://github.com/e-mission/e-mission-base/blob/master/www/js/splash/updatecheck.js#L151

and it stringifies the entire `updateResponse` instead of only displaying the build number.

Unfortunately, since that code is executed before any channel switch, I will have to fix it by pushing a new version of emTripLog. And if I do that, I will probably want to update all the plugins as well.

@asiripanich I can try to do that over the weekend from the airport since I won't have much else to work on. Thoughts on having to re-test the onboarding and data collection?

**Comment by asiripanich** [comment]
> 
> 
> yeah I figured it out yesterday, but didn't update because I was busy deploying the final fixes to the auto-labeling.
> Although both master and CEO ebike project have the same code, the main emTripLog is not built from either for those. It is built from https://github.com/e-mission/e-mission-base which is a stripped down version of the phone which has sensing and not UI.
> 
> And since it doesn't have the UI, I did not merge over the i18n changes. So the implementation there is:
> https://github.com/e-mission/e-mission-base/blob/master/www/js/splash/updatecheck.js#L151
> 
> and it stringifies the entire `updateResponse` instead of only displaying the build number.
> 
> Unfortunately, since that code is executed before any channel switch, I will have to fix it by pushing a new version of emTripLog. And if I do that, I will probably want to update all the plugins as well.
> 
> @asiripanich I can try to do that over the weekend from the airport since I won't have much else to work on. Thoughts on having to re-test the onboarding and data collection?

Sorry, I just saw this today. I don't think it's worth the risk. We are launching the study this week.

**Comment by shankari** [comment]
@asiripanich note that this has been tested in the CanBikeCO app, so it is not untested code. It is just that **you** haven't tested it.

**Comment by asiripanich** [comment]
If you think this will work on master then I'm happy to try.

**Comment by shankari** [comment]
@asiripanich these are native code changes, so you can't test them out unless you build the native app, or I push the changes to emTripLog. I was offering to push a new version of emTripLog with the changes. But the changes have to go through app review and once they are deployed, it will be hard to go back.

**Comment by shankari** [comment]
There is no initial download UI prompt any more.
