### ISSUE TITLE
Time-use Survey

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#675]
We are implementing the Time-use Survey which essentially like what is in diary tab but for the things that user do while not traveling.
The feature is based on Enketo Survey.

So I wonder should we re-use the `manual/survey_response` as our data model or is there a better place to save those data?

At the moment, `manual/survey_response` is saved in `usercache` collection.
I am using `BEMUserCache.put('manual/survey_response', data)` method for saving the data.
For retrieval, I use `UnifiedDataLoader.getUnifiedMessagesForInterval('manual/survey_response', tq)`.

Also, with this feature, I will be implementing the generic xml to json parser from Enketo survey response which should benefit whoever using/planning to the Enketo Survey feature.

**Comment by asiripanich** [comment]
For time use responses, I'm not planning to link it to location data (trips, places, etc.). Also, it is possible that one might records their time use during their commute (e.g., online shopping on a train), hence there will be overlapping time use responses and trip data.

The plan right now is to create a new tab called "Time use", a clone of the "Daily" tab, instead of mixing time use cards with trip cards in "Daily". Users can click on an add button which will launch an [Enketo time use questionnaire](https://ee.kobotoolbox.org/single/a70807b21be6817966eb54dd8df08c36), the activity start date field of the questionnaire is read-only and will be prefilled with the selected date of the date picker, once the response is submitted it will be used to display on the "Time use" tab just like regular trips.

**Comment by shankari** [comment]
@atton16 I have also been refactoring the survey code to be more modular
Please see https://github.com/e-mission/e-mission-docs/issues/674 and https://github.com/e-mission/e-mission-phone/pull/799

In particular, we have directives for the various types of surveys, and the code to populate and store the data will be confined to the directive. This ensures that changes to the implementation of one type of survey don't affect the others, and it ensures that we can add new survey types without modifying (and bulking up) the core list code.

If you could create a similar directive structure for the enketo survey, create a new `surveyOpt`, and set it up to be launched by the following code,

```
<linkedsurvey element-tag="{{surveyOpt.elementTag}}" trip="tripgj" class="row"></linkedsurvey>
```

I can merge it to master.

**Comment by shankari** [comment]
Note that I created the `surveyOpt` and the `linkedsurvey` tag (spending all of last afternoon on it) so that we could eventually create a config that could be changed without editing the code.

**Comment by asiripanich** [comment]
> 
> 
> @asiripanich @atton16 for the record, I would probably go with the second approach 😄

We are using the second approach. :)

**Comment by asiripanich** [comment]
> bulking

On the high level, how does this work with the code for populating labels for each survey response? if we use a new type of survey.

**Comment by asiripanich** [comment]
@shankari, how can we manipulate `metadata.write_ts` so that the activity start time can be used in the diary timeline instead of the entry creation time?

**Comment by fourstepdev** [comment]
> @asiripanich you should not manipulate the `metadata.write_ts`. That is a Bad Idea from a maintenance and reuse perspective.
> 
> @atton16 `UnifiedDataLoader.getUnifiedMessagesForInterval()` already supports querying on either `metadata.write_ts` or `data.ts`. I made the change when I implemented the label screen. I don't see any hardcoding of the field in the code, can you please link to what you are seeing?
> 
> In general, I would use the label screen as a starting point for your work and not the diary timeline.

I am sorry, it was the default value not the hardcode.

**Comment by shankari** [comment]
> What about I implement CRUD on the server side?

@atton16 @asiripanich I am not sure what you mean by this. I also don't know what part of the problem you are trying to solve. 

Are you trying to edit trips? In that case, CRUD won't work because it does not fit the data model. Please see my response above.

Are you trying to edit time use survey entries? In that case, you can just use the most recent entry and don't really need to delete.

So I am not sure what you are trying to do and what your actual proposal is. Particularly if you want to get this into master, I would suggest actually coming up with a short design document for my review.

**Comment by shankari** [comment]
@asiripanich since the survey is complete, can you close this?
