### ISSUE TITLE
Map Location Inaccurate (Not appearing on UI)

### ISSUE THREAD

**Issue by promie** [e-mission/e-mission-docs#786]
After the trip is confirmed, the `TO` and `FROM` locations inconsistently appears on some trips -- despite the refresh. This is also the same with the markers on the map. I've attached the screenshot of the confirmed trips where both the `TO` and `FROM` locations and the map markers are not visible.

![image](https://user-images.githubusercontent.com/92339996/187521635-4eb2df41-79f0-4486-ac62-c94b3ea1cb89.png)

**Comment by shankari** [comment]
@promie

In general, it is useful to send logs along with an issue so that I can get a sense of what is going on under the hood.
"Not working" 

For this specific issue, we load both the map tiles and the addresses using free services that have rate limits to avoid abuse. To avoid overloading the services, we stagger our reverse lookups, so the address may take some time to load

wrt map tiles loading, did you search for prior issues related to this - e.g. "map tiles not loading" fairly quickly finds
https://github.com/e-mission/e-mission-docs/issues/111

From the screenshot, it appears that you have tested this using a custom app version. Please check to see if the app has pulled all the fixes related to that issue from master.

**Comment by promie** [comment]
@shankari 

Thanks for the reply. As this is my first time creating an issue please excuse me for not following the standard procedure, I'll note it down for next time. 

Thanks a lot for provided links and explanation, I will do the investigation further and double check if our latest fork is up to date with the master branch.
