### ISSUE TITLE
How to show "Draft" trips into the "label view"?

### ISSUE THREAD

**Issue by idillon-sfl** [e-mission/e-mission-docs#920]
Hello !

Following [our performances issues](https://github.com/e-mission/e-mission-docs/issues/916), I upgraded the mobile app to the latest version.

After many challenges, I managed to have a "label view" almost identical in style and behavior to our "Diary view", but using "trip" instead of "tripgj".

Everything seemed to be working fine while I was working with my old trips. However, when I started having new trips, I noticed the "Draft" trips do not appear in the label view. I can still see them on the "diary view", but not into the "label view". I failed to find a solution to this. Do you have some clues?

It also seems like some trips get stuck on "Draft" even after launching the data analysis several times (I will need to use the app longer before I can describe better). We have two servers. One with the latest e-mission-server commit, and one other with a version of august 2021. I've seen this on both of them. Have you ever encountered that problem?

Thank you

**Comment by shankari** [comment]
The main app currently has both diary and label views for just this reason. For the common case, the label view is enough, since the trips will eventually show up there after they are processed. If people want to see trips immediately, they can use diary view.

If you search the existing issues and PRs, you will find that we have an existing issue
https://github.com/e-mission/e-mission-docs/issues/902
and related PR
https://github.com/e-mission/e-mission-docs/issues/902
to unify the two

However, the unified PR is still being tested and is not on production for us.

> After many challenges, I managed to have a "label view" almost identical in style and behavior to our "Diary view", but using "trip" instead of "tripgj".

What were the challenges? It would be helpful to the community if you shared the challenges and the solutions, and potentially even contributed them to the base repo.

> It also seems like some trips get stuck on "Draft" even after launching the data analysis several times. Have you ever encountered that problem?

This means that there is an issue with the pipeline. You need to look at the pipeline logs and see what is failing.
There are several issues filed for pipeline debugging, primarily by @ericafenyo and we have also discussed it at the previous  technical group meetings. You might want to search for the error, or file a new issue if you do not find it.

**Comment by idillon-sfl** [comment]
Thank you!

Now I am thinking the issue with the pipeline might be that I've been reusing the same token a lot while creating new users and using different versions of the app. I'll try with fresh new tokens and investigate the logs further later.

> What were the challenges? It would be helpful to the community
e-mission-phone changed a lot since our branches diverged. The process to integrate all the changes broke a lot of our stuff, which had to be repaired. In the beginning I wanted to update only the "infinite scroll", but I found myself having to update also a lot of dependencies, for in the end having to update everything.
Also, adding our daily survey into the "infinite scroll" did not work very well. The infinite scroll was probably not intended for that. [Our branch](https://github.com/FabmobQC/mamobilite/tree/update-to-last) could show some clues to someone who would like to do the same.

I'll ask my team if I should spend more time trying to display the "draft" trips.

**Comment by idillon-sfl** [comment]
So [it seems](https://github.com/e-mission/e-mission-docs/issues/902#issuecomment-1558376088) @JGreenlee managed to display the "draft" trips on the label views.

I struggle to find the branch where it should be. Should I expect to find it on [label-screen-react-migration](https://github.com/JGreenlee/e-mission-phone/blob/label-screen-react-migration)?

Thank you!

**Comment by shankari** [comment]
> e-mission-phone changed a lot since our branches diverged. The process to integrate all the changes broke a lot of our stuff, which had to be repaired. In the beginning I wanted to update only the "infinite scroll", but I found myself having to update also a lot of dependencies, for in the end having to update everything.

Yes, e-mission is continuously evolving. It is probably worthwhile to keep an eye on the big changes, be familiar with the roadmap, and integrate fairly frequently. Note also that the label screen has been around since January 2021. So again, with familiarity with the roadmap, you might have chosen to add your survey functionality to the newer screen and not the deprecated one.

When you do integrate, at least now, it is probably easiest to pull all the functionality and cherry-pick your changes into it. We are creating individual components as we migrate to react, not sure what it will look like after that is done.

> Also, adding our daily survey into the "infinite scroll" did not work very well. The infinite scroll was probably not intended for that

As you might remember from the meeting with USNW, the infinite scroll has the ability to display full-fledged, ODK-compatible surveys. Adding a new survey should be as simple as building a new `MMButton` directive, similar to `multilabel` and `enketo`.

You are, of course, welcome to implement functionality in any way that you want, but for long-term maintenance, it would probably be easier to fit into our existing UX, including submitting your code as a module to the main repo and getting reviews from @JackGreenlee and me rather than working on a separate branch.

Hopefully, the react migration will help with that modularity as well!

**Comment by shankari** [comment]
> Now I am thinking the issue with the pipeline might be that I've been reusing the same token a lot while creating new users and using different versions of the app. I'll try with fresh new tokens and investigate the logs further later.

Could be. You could also try turning off the assertions in `conf/analysis/` to see if it helps.

**Comment by JGreenlee** [comment]
> So [it seems](https://github.com/e-mission/e-mission-docs/issues/902#issuecomment-1558376088) @JGreenlee managed to display the "draft" trips on the label views.
> 
> I struggle to find the branch where it should be. Should I expect to find it on [label-screen-react-migration](https://github.com/JGreenlee/e-mission-phone/blob/label-screen-react-migration)?
> 
> Thank you!

@idillon-sfl Yes, I implemented draft trips on the Label screen, along with a few other features that were specific to the Diary screen. This was in order to remove the Diary screen before migrating to React Native.

That was part of https://github.com/e-mission/e-mission-phone/pull/974. That PR is VERY large, so I will point you to the specific commit that is most relevant to draft trips: https://github.com/e-mission/e-mission-phone/pull/974/commits/67f40f20afb6ee117196a5d8a1a62d19e12ea200.

This has not yet been included in any OpenPATH release yet, but it should be soon.


> e-mission-phone changed a lot since our branches diverged.

With the ongoing migration, `e-mission-phone` will be rapidly changing even more. Virtually everything in the UI will be rewritten over the next few months, and the native plugins after that. It is up to you and your team what you wish to do with `mamobilite`, but maybe it would interest you to re-implement the functionality you need and PR it back here on e-mission-phone. I am not sure how much your fork differs currently, but you may find this approach easier than separately maintaining a different fork.
We are happy to coordinate with you and discuss what functionality you currently find missing from e-mission-phone.

**Comment by idillon-sfl** [comment]
Thank you a lot!

It seems these changes would require to update the server in order to have . We'll still wait a couple of weeks before updating the server.

Yes, I realize the migration to React will also be quite a challenge. I am a bit anxious about it, but at the same time it sounds like a very good move. 

> Could be. You could also try turning off the assertions in conf/analysis/ to see if it helps.
It seems everything is already on `false`

It seems the trips are not stuck on "Draft", but just stay as such for longer than before. We'll do with it for the moment, and eventually update the server. Thank you.
